### ISSUE TITLE
CTJ: UI/UX Meeting Weekly Agenda

### ISSUE THREAD

**Issue by jenchuu** [hackforla/CivicTechJobs#135]
### Overview

Template for our meetings from now on:

[DATE] Agenda and Notes

### Prework
- [ ] Add prework here

#### Recurring items: Happens on the UX/UI meeting
 - [ ] review any issues that are in the [new issue approval column](https://github.com/hackforla/design-systems/projects/1#column-15133576)

 - [ ] Accountability and Support Check.
    - [ ] Review assignments for each PM
       - [ ] [Bernard](https://github.com/hackforla/UI-UX/issues/88)
       - [ ]  [Wataru Inoue](https://github.com/hackforla/UI-UX/issues/189)
       - [ ] [Ryan] (https://github.com/hackforla/UI-UX/issues/67)

#### New Items
- [ ] 
#### Task items from Team meeting to review
- [ ] 
  - [ ] Carry forward the "New Items" that we did not get to look at today

### Notes from meeting
- 

### Action Items

z

### Resources/Instructions

[Resources](https://github.com/hackforla/CivicTechJobs/wiki/Resources)

**Comment by jenchuu** [comment]
## 2/01 Agenda and Notes

### Prework
- [ ] Create and post [UXD open role card on UI/UX GitHub](https://github.com/hackforla/UI-UX/projects/3#card-77034347)

### Roll Call

#### Recurring items
 - [ ] Review [Issues in progress](https://github.com/hackforla/CivicTechJobs/projects/1#column-10928272)

 - [ ] Accountability and Support Check
    - [ ] Update from Patty and Helene https://github.com/hackforla/CivicTechJobs/issues/12
    - [ ] 

#### New Items
- [ ] Designate note taker for today's meeting
- [ ] Discuss potentially new UXD/UXR meeting date
- [ ] 

#### Task items from Team meeting to review
- [ ] TBD
  - [ ] Carry forward the "New Items" that we did not get to look at today


### Notes from meeting
- 

### New Task Items

#### Items for next week's agenda

**Comment by jenchuu** [comment]
## Feb 08, 2022 Agenda and Notes

### Prework
- [x] Create and post [UXD open role card on UI/UX GitHub](https://github.com/hackforla/UI-UX/projects/3#card-77034347) to recruit 2 UXDs

### Roll Call
#### Recurring items
 - [ ] Review [Issues in progress](https://github.com/hackforla/CivicTechJobs/projects/1#column-10928272)
 - [ ] Accountability and Support Check
    - [ ] Update from Grace on meeting with Bonnie and PMs regarding flow

#### New Items
- [ ] Designate note taker for today's meeting
- [ ] Discuss edits needed to flow
- [ ] Decide which designs are done to prectangle and handoff to Ava

#### Task items from Team meeting to review
- [ ] TBD
  - [ ] Carry forward the "New Items" that we did not get to look at today


### Notes from meeting

### New Task Items
- [ ] 

#### Items for next week's agenda

**Comment by jenchuu** [comment]
## Feb 15, 2022 Agenda and Notes

### Prework

### Roll Call
#### Recurring items
 - [ ] Review [Issues in progress](https://github.com/hackforla/CivicTechJobs/projects/1#column-10928272)
 - [ ] Accountability and Support Check
    - [ ] 
#### New Items
- [ ] Designate note taker for today's meeting
- [ ] Janzen to create issue or link to existing issue for Google form banner.. Ask PMs and UXRs
- [ ] Edit CMS wireframes?

#### Task items from Team meeting to review
- [ ] Discuss w/ Janzen about banner edits
- [ ] Decide which designs are now done to prectangle and handoff to Ava
- [ ] Discuss edits to MVP designs and use time as working session
  - [ ] Carry forward the "New Items" that we did not get to look at today


### Notes from meeting

### New Task Items
- [ ] 

#### Items for next week's agenda

**Comment by jenchuu** [comment]
## Feb 22, 2022 Agenda and Notes

### Prework

### Roll Call
#### Recurring items
 - [ ] Review [Issues in progress](https://github.com/hackforla/CivicTechJobs/projects/1#column-10928272)
 - [ ] Accountability and Support Check
    - [ ] 
#### New Items
- [ ] Designate note taker for today's meeting
- [ ] Edit prototype and handoff to UXRs to begin testing


#### Task items from Team meeting to review
- [ ] TBD
- [ ] Decide which ELEMENTS are now done to prectangle and handoff to Ava
- [ ] 
  - [ ] Carry forward the "New Items" that we did not get to look at today


### Notes from meeting
UI/UX CTJ Meeting (6PM PST) - Notes taken by 


### New Task Items
- [ ] TBD

#### Items for next week's agenda

**Comment by jenchuu** [comment]
## Mar 01, 2022 Agenda and Notes

### Prework

- [ ] Finish prototype

### Roll Call
#### Recurring items
 - [ ] Review [Issues in progress](https://github.com/hackforla/CivicTechJobs/projects/1#column-10928272)
 - [ ] Accountability and Support Check
    - [ ] 
#### New Items
- [ ] Designate note taker for today's meeting
- [ ] Finish making hamburger mobile menu

#### Task items from Team meeting to review
- [ ] Decide which ELEMENTS are now done to prectangle and handoff to Ava
  - [ ] Carry forward the "New Items" that we did not get to look at today


### Notes from meeting
UI/UX CTJ Meeting (6PM PST) - Notes taken by 

### New Task Items
- [ ] TBD

#### Items for next week's agenda

**Comment by jenchuu** [comment]
## Mar 08, 2022 Agenda and Notes

### Prework

- [ ] Edit and finish prototype for usability testing

### Roll Call
#### Recurring items
 - [ ] Review [Issues in progress](https://github.com/hackforla/CivicTechJobs/projects/1#column-10928272)
 - [ ] Accountability and Support Check
    - [ ] @eva32lee Component - disclaimer banner
    - [ ] @graceerya Component - progress bar
    - [ ] @janzenmolina Component - Sticky bar
    - [ ] @jenchuu Component - Text fields

#### New Items
- [ ] Designate note taker for today's meeting

#### Task items from Team meeting to review
- [ ] 
  - [ ] Carry forward the "New Items" that we did not get to look at today


### Notes from meeting
UI/UX CTJ Meeting (6PM PST) - Notes taken by 

### New Task Items
- [ ] TBD

#### Items for next week's agenda

**Comment by jenchuu** [comment]
## Mar 15, 2022 Agenda and Notes

### Prework
- [ ] Create issue for Design System additions
- [ ] Create issue for footer color
- [ ] Create issue for mobile filter design
- [ ] Create issue for Availability filter design (pop up, etc.)

### Roll Call

#### Recurring items: Happens on the UX/UI meeting
 - [ ] Review [Issues in progress](https://github.com/hackforla/CivicTechJobs/projects/1#column-10928272)
 - [ ] Accountability and Support Check
    - [ ] Review assignments for each Designer

#### New Items
- [ ] Discuss usability test
- [ ] Discuss affinity mapping session on Thurs (Figjam)
- [ ] Discuss CMS testing

#### Task items from Team meeting to review
- [ ] 
  - [ ] Carry forward the "New Items" that we did not get to look at today

### FYI

### Notes from meeting
- 

### New Task Items

#### Items for next week's agenda

**Comment by jenchuu** [comment]
## Mar 22, 2022 Agenda and Notes

### Prework
- [ ] Finish affinity mapping session with UXRs

### Roll Call

#### Recurring items: Happens on the UX/UI meeting
 - [ ] Review [Issues in progress](https://github.com/hackforla/CivicTechJobs/projects/1#column-10928272)
 - [ ] Accountability and Support Check
    - [ ] Review assignments for each Designer

#### New Items
- [ ] Create issues for design revisions based on priority/effort
    [ ] Pick up one issue at a time from prioritized backlog and complete (then can pick up another issue)

#### Task items from Team meeting to review
- [ ] 
  - [ ] Carry forward the "New Items" that we did not get to look at today

### Notes from meeting
- 

### New Task Items

#### Items for next week's agenda

**Comment by jenchuu** [comment]
## Mar 29, 2022 Agenda and Notes

### Roll Call

#### Recurring items: Happens on the UX/UI meeting
 - [ ] Review [Issues in progress](https://github.com/hackforla/CivicTechJobs/projects/1#column-10928272)
 - [ ] Accountability and Support Check
    - [ ] Review assignments for each Designer

#### New Items
- [ ] Wireframe solutions to make "how to join" process clear and easily findable for new visitors

#### Task items from Team meeting to review
- [ ] 
  - [ ] Carry forward the "New Items" that we did not get to look at today

### FYI

### Notes from meeting
- 

### New Task Items

#### Items for next week's agenda

**Comment by jenchuu** [comment]
## [DATE] Agenda and Notes

### Prework
- [ ] Add prework here

### Roll Call

#### Recurring items: Happens on the UX/UI meeting
 - [ ] Review (https://github.com/hackforla/CivicTechJobs/projects/1#column-10928272)
 - [ ] Accountability and Support Check
    - [ ] Review assignments for each Designer

#### New Items
- 

#### Task items from Team meeting to review
- [ ] 
  - [ ] Carry forward the "New Items" that we did not get to look at today

### FYI

### Notes from meeting
- 

### New Task Items

#### Items for next week's agenda

**Comment by jenchuu** [comment]
## April 07, 2022 Agenda and Notes

### Roll Call

#### Recurring items: Happens on the UX/UI meeting
 - [ ] Review [Issues in progress](https://github.com/hackforla/CivicTechJobs/projects/1#column-10928272)
 - [ ] #209 
 - [ ] Accountability and Support Check
    - [ ] Review assignments for each Designer

#### New Items
- [ ] Wireframe solutions to make "how to join" process clear and easily findable for new visitors

#### Task items from Team meeting to review
- [ ] 
  - [ ] Carry forward the "New Items" that we did not get to look at today

### FYI

### Notes from meeting
- 

### New Task Items

#### Items for next week's agenda

**Comment by jenchuu** [comment]
## [May 17, 2022] Agenda and Notes

### Prework
- [ ] Reprioritize and assign issues to designers
- [ ] Create a new issue to include "How to join" on the landing page

### Roll Call

#### Recurring items: Happens on the UX/UI meeting
 - [ ] Review [Issues in progress] (https://github.com/hackforla/CivicTechJobs/projects/1#column-10928272)
 - [ ] Accountability and Support Check
    - [ ] Review assignments for each Designer

#### New Items
- [ ] Assign Qualifier role page edits (remove banner and other edits)
- [ ] Assign Qualifier calendar page edits
- [ ] Assign Search results page edits
- [ ] Assign Credits page creation

#### Task items from Team meeting to review
- [ ] 
  - [ ] Carry forward the "New Items" that we did not get to look at today

### FYI

### Notes from meeting
- 

### New Task Items

#### Items for next week's agenda

**Comment by sabheasley** [comment]
Hello @jenchuu! Can you please provide an update here prior to our Tuesday meeting:
1. Progress
2. Blockers
3. Availability
4. ETA

**Comment by kcoronel** [comment]
Hey @jenchuu, can we restart the use of this agenda for your weekly meetings with Design - I think this will be helpful as we transition PM's. We can chat about simplifying the agenda/notes if it is helpful. TY! 

copying @sabheasley for visibility

**Comment by kcoronel** [comment]
Hey @fenglugithub, this is the issue for your Design Team agendas. Let me know if you want to change any of the formatting.

**Comment by fenglugithub** [comment]
## [Mar 27, 2022] Agenda and Notes

### Prework
- [ ] Working session for Qualifier page
- [ ] Refine the search page
- [ ] Brainstorm ideas for the availability calendar - mobile version

### Roll Call

#### Recurring items: Happens on the UX/UI meeting
 - [ ] Accountability and Support Check
     - [ ] Review assignments for each Designer [Design issues in progress](https://github.com/hackforla/CivicTechJobs/projects/1?card_filter_query=design#column-10928272)
 
#### New Items
- [ ] Finalize the search result page
- [ ] Design solutions for availability calendar - mobile version
- [ ] User flow

#### Task items from Team meeting to review
- [ ] 
  - [ ] Carry forward the "New Items" that we did not get to look at today

### FYI
- 

### Notes from meeting
- 

### New Task Items
- 

#### Items for next week's agenda

**Comment by ExperimentsInHonesty** [comment]
test - bobsee

**Comment by kcoronel** [comment]
Notes re: CMS 
@kcoronel audit how long the project description is going 
@jaason-shi @brandonhu8 can you ask at the next PM meeting if folks have templates of their job descriptions? 

For Devs: 
- Need to know how often devs want to clean up archive job postings in CMS 

For UXR: 
- To test with PM's skill choices & also the deleting of past role postings

**Comment by kcoronel** [comment]
<img width="330" height="715" alt="Image" src="https://github.com/user-attachments/assets/f792eb00-cbaf-4823-8458-312f3fda6824" />

**Comment by kcoronel** [comment]
Recruit role poster on the top skills needed for each role. 
@xliu5899 could you give us your perspective on sample size 
Usability testing for the Search Results Page 
- newly joined volunteers

Testing in staging site or interactive prototype testing? Staging site is the least amount of effort.

**Comment by Rabia2219** [comment]
- https://github.com/hackforla/CivicTechJobs/issues/727
