### ISSUE TITLE
UX Researcher agenda 2-4-22

### ISSUE THREAD

**Issue by patula006** [hackforla/CivicTechJobs#140]
•	Merge Bonnie’s volunteer survey with our survey
Proposed updated onboarding survey once Bonnie is back from medical leave: https://docs.google.com/forms/d/e/1FAIpQLSf-FyHf_0l98YT_RtE8vTnbvXuoUg0slYE2eGfybdyo_WL4kg/viewform

Current onboarding survey: https://docs.google.com/forms/d/e/1FAIpQLScXnJSyCXgO_RCAuCyOkG4sqGILpAepTlJ0HOaK4H_ccEVmNw/viewform

•	Validate user flow (Github #76 – to be updated next week) – the PMs asked that this be our priority; the latest is that folks can login to save their screener info so that it doesn’t have to be re-entered later – but is this ideal? Discuss research plan for this.
•	Research plan – pre-MVP (before it goes live) – meet with PMs to get a sense of what the CMS should look like (where they will enter new roles); what else should we research pre-MVP?
We can do a concept validation exercise - let's discuss
•	Research plan post-MVP (after it’s live) – this is what Stephanie has been working on – let’s further discuss

**Comment by sdimran** [comment]
Hi Patty, I think this is great to have a UX Researcher agenda for your team meetings 👍🏽 . can you transition this into a similar format of our all team meetings? this way we can keep a track of all discussion points and action items each week in the comments. ticket for reference  : https://github.com/hackforla/CivicTechJobs/issues/16

if you need any help getting that format please let me know, the UX and Dev have separate Github issues for their team meetings as well

**Comment by patula006** [comment]
I did have a separate agenda that was really more of a placeholder (and I was going to delete it) but I don't see it anymore so I don't know if you are referring to that or this format which I got from Jen. Please let me know. Thanks!

**Comment by stephaniestahlberg** [comment]
02/15/22

Participants: @stephaniestahlberg @patula006 @Dendorable 

Agenda:
- [ ] Survey updates
- [ ] CMS wireframe updates
- [ ] Usability testing planning
- [ ] Stephanie to share CTJ account details for Zoom and Calendly

Notes:
* Survey has been updated as per Bonnie's feedback and will be reviewed again this Sunday
* Researchers have reviewed the CMS wireframes and prepared feedback for Sharad at the next CMS-dedicated meeting
* Zoom and Calendly accounts are ready to use for usability testing interviews
* Stephanie will finish editing the usability testing script based on team feedback on mock session

**Comment by sdimran** [comment]
2/2/22

 Agenda and Notes

Prework
NA

Roll Call
Stephanie, Helene, Patty

Agenda

New volunteer survey status

Validate user flow (Github https://github.com/hackforla/CivicTechJobs/issues/76 – to be updated next week) – the PMs asked that this be our priority; the latest is that folks can login to save their screener info so that it doesn’t have to be re-entered later – but is this ideal? Discuss research plan for this.
We can do a concept validation exercise - let's discuss

Research plan – pre-MVP (before it goes live) – meet with PMs to get a sense of what the CMS should look like (where they will enter new roles); what else should we research pre-MVP?

Research plan post-MVP (after it’s live) – this is what Stephanie has been working on – let’s further discuss

Notes from meeting

Helene finished her C + C analysis of volunteer websites and how they look if you are a new volunteer looking for a role; she summarized her findings for us and will present to the team on Tuesday
Patty is to start working on a survey to give to PMs using our CMS for posting roles; to be based on her C + C analysis of posting roles to various volunteer websites; post in PM Slack channel and / or have our PMs help us disseminate
Started crafting a research plan for testing the user flow of the MVP (volunteer-facing side) for when all the pages are designed and we have working prototypes; ideally, we test mobile and desktop versions with different groups if we get enough participants; planning to attend an on-boarding and recruit from there
Stephanie has finished the volunteer survey and it's ready for Bonnie to approve and deploy - see: https://docs.google.com/forms/d/1DnyqzfvH5QPSjGLtcvq-n_MhcQ_kxNxddi5D01DVBks/edit; see also https://github.com/hackforla/CivicTechJobs/issues/125
We will each try to find research on whether it's ideal (or not) to ask volunteers to login when doing the screener in order to save their information - should have data to back up best practices
New Task Items

Look for secondary research on requiring a login when visiting a page - does this help or hinder?
Patty to start designing a survey for the PMs using the CMS based on her C + C analysis
Helene to summarize her C + C on looking for volunteer roles at the Tuesday meeting
Start research plan for testing the MVP user flow

**Comment by stephaniestahlberg** [comment]
03/01/22

Participants: @stephaniestahlberg @patula006

Agenda:

- [ ] Discuss plan for CMS research and assign tasks
- [ ] Make a list of items to be discussed with Bonnie tomorrow
- [ ] Usability testing planning

Notes:

* Patty will lead the CMS script for testing. Stephanie will add questions to be used for metrics.
* Items to be discussed with Bonnie are: Slack recruiting message for new volunteers, recruiting process for CMS research, Zoom links to be used for usability testing, and review and approval of new volunteer survey
* UXR and designers will meet on Friday to look at the final version of prototypes for testing. Testing will begin as soon as Saturday (calendar will allow participants to sign up between 3/5 and 3/13)
* Stephanie will add the "How to join" page into the usability testing script

**Comment by stephaniestahlberg** [comment]
03/08/22

Participants: @stephaniestahlberg @patula006 @Dendorable 

Agenda:

- [ ] "New volunteer" usability testing schedule based on participant sign-ups
- [ ] Discuss and finalize CMS research script
- [ ] Make a recruiting plan for the CMS research

Notes:

**Comment by stephaniestahlberg** [comment]
## 3/15/22  Meeting agenda

### Prework to prep for meeting

### New items

- [ ] Define a reporting format for usability testing findings
- [ ] Agree on a plan for the UXD-UXR working session on Friday
- [ ] Discuss CMS research testing schedule

### Notes from meeting

### Task items

**Comment by stephaniestahlberg** [comment]
## 3/22/22  Meeting agenda

### Prework to prep for meeting

### New items

- [ ] Introduce ourselves and the project to a potential new team member (Lihui)
- [ ] Discuss the usability testing findings presentation - what went well, any changes for the future
- [ ] Updates on CMS research
- [ ] Schedule a meeting to work on CMS analysis and generate list of insights and recommendations

### Notes from meeting
*

**Comment by stephaniestahlberg** [comment]
## 3/29/22  Meeting agenda

### New items

- [ ] Discuss the CMS presentation
- [ ] Answer questions the new team members might have

### Notes from meeting

**Comment by stephaniestahlberg** [comment]
## 4/12/22  Meeting agenda

### New items

- [ ] Discuss the CMS presentation
- [ ] Plan out future research: CTJ metrics, new volunteer survey, next round of usability testing

### Notes from meeting
-

**Comment by stephaniestahlberg** [comment]
## 4/26/22  Meeting agenda

### New items

- [ ] Discuss good presentation practices
- [ ] Summer to share ideas for presenting the "new volunteer survey" results (issue [#171](https://github.com/hackforla/CivicTechJobs/issues/171))
- [ ] Go over Github guidelines, answer questions for new UXRs

### Notes from meeting
-

**Comment by stephaniestahlberg** [comment]
## 6/28/22  Meeting agenda

### New items

- [ ] Discuss joining a designers' meeting to see how they work and ideate
- [ ] Concept testing vs. usability testing
- [ ] New research project ideas: 
1) To uncover why some people check out Hack for LA but decide not to sign up. Why: to identify areas where HfLA's public sites could improve to attract more volunteers to sign up.
2) [Usability benchmarking](https://www.nngroup.com/articles/product-ux-benchmarks/#:~:text=UX%20benchmarking%20is%20the%20process,testing%2C%20analytics%2C%20or%20surveys.). Why: plan ahead for continuously tracking metrics on CTJ to evaluate the product's performance over time.
3) [First-click testing](https://www.userinterviews.com/ux-research-field-guide-chapter/first-click-testing) on CTJ's landing page. Why: when the first click is correct, users are 2-3 times more likely to complete the entire task.

### Notes from meeting

**Comment by stephaniestahlberg** [comment]
## 7/12/22  Meeting agenda

### New items

- [ ] Discuss socializing findings from the new volunteer survey
* With the org's leadership
* With the design team once new designers are recruited

[Article](https://www.answerlab.com/insights/creative-approaches-to-socialize-research-insights-and-build-empathy) on the importance of socializing research insights with some great ideas (although at HfLA we will probably keep it simple!)
- [ ] Handing off the metrics surveys - github issues [206](https://github.com/hackforla/CivicTechJobs/issues/206) and [238](https://github.com/hackforla/CivicTechJobs/issues/238) 
- [ ] Discuss recruiting for new UXR team members

### Notes from meeting

**Comment by hkimsummer** [comment]
**7/19/22 Meeting agenda**

New items

- [ ] Meet and greet with Adrienne and Nina 
- [ ] Give overview of project stage and upcoming research 
- [ ] Answer any questions they have 

Notes from meeting

**Comment by hkimsummer** [comment]
## 7/19/22 Meeting agenda

### New items

- [ ] Discuss analysis plan for #238 
- [ ] Discuss potential future research (accessibility)

### Notes from meeting

**Comment by hkimsummer** [comment]
## 8/16/22 Meeting agenda

### New items

- [ ] Discuss analysis and presentation plan for #238, to be presented by Adrienne on 8/23 
- [ ] Discuss research plan for Qualifier Page usability testing

### Notes from meeting

**Comment by hkimsummer** [comment]
## 8/30/22 Meeting agenda

### New items

- [ ] Discuss logistics for usability testing sessions for #291 

### Notes from meeting

**Comment by hkimsummer** [comment]
## 9/13/22 Meeting agenda

### New items

- [ ] Discuss presentation 
- [ ] Go over GitHub

### Notes from meeting

**Comment by melkosm** [comment]
9/20/22 Meeting agenda

- [ ] Discuss handover items for project
- [ ] Discuss new UXR Lead
- [ ] Create handover document

**Comment by melkosm** [comment]
10/4/22 

- [ ] Search for new team member for October usability testing
- [ ] Review 2021 PM recordings- list requirements
- [ ] Go over former research in gdrive (build context)

**Comment by melkosm** [comment]
10/11/22

- [ ] Recruit new team member for October usability testing
- [ ] Go over former research in gdrive (build context)
- [ ] Clarify github and research template asks from Bonnie

**Comment by melkosm** [comment]
- [ ] Onboard Genggeng- product requirements, roadmap, work/research done and to be done
- [ ] Discuss October tasks and dependencies- search page, role skills and experience, usability testing
- [ ] Go over PM recording insights

**Comment by melkosm** [comment]
10/25/2022
- [ ] Discuss Research gdrive folders- usability-preference testing
- [ ] Track overview in research summary doc
- [ ] Discuss with UXR team about weekly meeting with UXD

**Comment by melkosm** [comment]
11/1/2022

- [ ] Go through CMS folder and discuss materials and content of 1st iteration

**Comment by melkosm** [comment]
11/8/2022

- [ ] Meet with UXD team to discuss CMS page
- [ ] Brainstorm to be better understand what insights are needed to moved forward with design development process

11/15/2022

- [ ] Prepare survey on current recruitment methods and job posting needs and behaviors
- [ ] Recruit PMs and TLs through Slack

11/22/2022

- [ ] Thanksgiving- no meeting

11/29/2022

- [ ] Close off survey
- [ ] Synthesize and analyze results
- [ ] Prepare presentation deck of CMS recruiting and job posting survey results
- [ ] Present insights to team

**Comment by melkosm** [comment]
1/11/2023

[ ] Availability moving forward
[ ] Overview of items to keep on our radar (job posting (feature list?), accessibility, test environment of website)
[ ] Onboarding- former research done on mvp- context of accessibility and cms moving forward

**Comment by kcoronel** [comment]
hi @jayywu - can you please begin using this agenda issue for your weekly meetings with your team. - I think this will be helpful as we transition PM's. We can chat about simplifying the agenda/notes if it is helpful. TY!

copying @sabheasley for visibility

**Comment by kcoronel** [comment]
September 27, 2023 

### Agenda Items: 
- [ ] hello
- [ ] hello 

### Notes from Meeting:

**Comment by kcoronel** [comment]
Make this an issue: 
All PII related docs including consent forms & interview recordings need to be stored in a 'locked drive.' Contact Admin channel & they can set you up with the same.
You don't need to keep the videos if the team does not need to. It can be destroyed after the data analysis & report writing. But irrespective of this, all protocols regarding consent forms+locked drive need to be followed. You will also need to mention in the consent forms how your data is going to be collected, handled, stored, deleted/destroyed (i.e the entire end-to-end data collection+storage process)
For other projects, we have used Hack for LA's Zoom account (to follow best practices including safety, privacy of participants). The available + free days/timings on all HfLA Zooms are on 1Password. There is a spreadsheet wherein you can identify the available days/timings. The PMs & Leads of your project would be aware of this spreadsheet & should be able to help you out.
There is a video submission sheet that projects have used after the video/audio interview. This is a good way to keep track of all the researchers and their respective interviews as they submit them to the locked drive: https://drive.google.com/drive/folders/1eOxxLQoGV6Ca7gEesE2SlG-fHWgRZb-G
I was wondering if you can shed some light on these deliverables. I am taking more of the Research Operations role for the team and want to see if we can implement some of these best practices during our testing phase.

**Comment by ngadoq** [comment]
**October 19, 2023**
Leah
Nga

**Agenda Items:**
 
- [ ] Findings from CMS usability test
- [ ] Report outline for CMS usability test
- [ ] CTJ Skills Matrix timeline

**Comment by kcoronel** [comment]
## [Date] Agenda and Notes

### Prework
- [ ] Check landing page [https://civictechjobs.org/]

### Roll Call

#### Recurring items: Happens on the PM Sunday meeting
 - [ ] Accountability and Support Check.
    - [ ] Review assignments for each PM
       - [ ] [Jen](https://github.com/hackforla/CivicTechJobs/issues/assigned/jenchuu) - UX/UI Designer Lead   
       - [ ] [J Wu](https://github.com/hackforla/CivicTechJobs/issues/assigned/jayywu) - UX/UI Research Lead
       - [ ] [Bitian](https://github.com/hackforla/CivicTechJobs/issues/assigned/bzzz-coding) - Dev. Co-lead
       - [ ] [Matt](https://github.com/hackforla/CivicTechJobs/issues/assigned/MattPereira) - Dev. Co-lead
       - [ ] [Karen](https://github.com/hackforla/CivicTechJobs/issues/assigned/kcoronel)
       - [ ] [Sabrina](https://github.com/hackforla/CivicTechJobs/issues/assigned/sabheasley)
       - [ ] [Kanika](https://github.com/hackforla/CivicTechJobs/issues/assigned/kchotani)
- [ ] continue adding labels to the issue that are still missing them (see audit links above)


#### New Items
- [ ] 
- [ ] Make new agenda for next week
  - [ ] Carry forward the "New Items" that we did not get to look at today

#### FYIs

#### Notes from meeting

#### Items for next week's agenda

**Comment by kcoronel** [comment]
## [Date] Agenda and Notes

### Prework
- [ ] Add any prework here

### Roll Call
-

#### Recurring Items: Happens on the UXR meeting
 - [ ] Accountability and Support Check
    - [ ] Review assignments for each Researcher [UXR issues in progress](https://github.com/hackforla/CivicTechJobs/projects/1?card_filter_query=uxr)

#### New Items
- [ ] 
- [ ] Make new agenda for next week

#### Task items from Team meeting to review
- [ ] 
  - [ ] Carry forward the "New Items" that we did not get to look at today

#### FYI
-

#### Notes from meeting
- 

### New Task Items
- 

#### Items for next week's agenda

**Comment by kcoronel** [comment]
## [Date] Agenda and Notes

### Prework
- [ ] Add any prework here

### Roll Call
-

#### Recurring Items: Happens on the UXR meeting
 - [ ] Accountability and Support Check
    - [ ] Review assignments for each Researcher [UXR issues in progress](https://github.com/hackforla/CivicTechJobs/projects/1?card_filter_query=uxr)

#### New Items
- [ ] 
- [ ] Make new agenda for next week

#### Task items from Team meeting to review
- [ ] 
  - [ ] Carry forward the "New Items" that we did not get to look at today

#### FYI
-

#### Notes from meeting
- 

### New Task Items
- 

#### Items for next week's agenda

**Comment by xxl228** [comment]
### July 26, 2024 Agenda and Notes 

**Roll Call**

- Vivian
- Manju

Recurring Items: Happens on the UXR meeting

- [ ] Accountability and Support Check
      Review assignments for each Researcher [UXR issues in progress](https://github.com/hackforla/CivicTechJobs/projects/1?card_filter_query=uxr)

New Item

- [ ] Usability Testing for CTJ skills page issue #532 

- [ ] Make a new agenda for next week's team meeting


Meeting Notes

- Finalized the usability research plan
- Finalized the draft screener, put it in google forms, only needs to add the date and time
- Reached out to Design to receive the final prototype
- Discussed pilot testing plan 

New Task Item

- [ ] Determine time for pilot testing
- [ ] Recruit pilot testing volunteers, perhaps from the project team

**Comment by xxl228** [comment]
### August 2, 2024 Agenda and Notes 

**Roll Call**

- Vivian
- Manju

Recurring Items: Happens on the UXR meeting

- [ ] Accountability and Support Check
      Review assignments for each Researcher [UXR issues in progress](https://github.com/hackforla/CivicTechJobs/projects/1?card_filter_query=uxr)

New Item

- [ ] Usability Testing for CTJ skills page issue #532 

- [ ] Make a new agenda for next week's team meeting

New Task Item

- [ ] Determine time for pilot testing
- [ ] Recruit pilot testing volunteers, perhaps from the project team

**Comment by xxl228** [comment]
## [Date] Agenda and Notes
-Conducted pilot test with new member, who has not seen the prototype, to finalize testing materials
-Assigned tasks for next meeting
### Prework
- [ ] Add any prework here
- Met with design and updated messages in the prototype

### Roll Call
-Vivian
-Rishi

#### Recurring Items: Happens on the UXR meeting
 - [ ] Accountability and Support Check
    - [ ] Review assignments for each Researcher [UXR issues in progress](https://github.com/hackforla/CivicTechJobs/projects/1?card_filter_query=uxr)


#### Task items from Team meeting to review
- [ ] 
  - [ ] Carry forward the "New Items" that we did not get to look at today


#### Notes from meeting
- Pilot tested the usability testing script, screener, research questions, links to prototype, with Rishi
- Still need to finalize more details before recruitment, see details in #532 

### New Task Items
- [ ] See details in #532 
- [ ] Follow up with Karen and Nooria for the secured google drive
- [ ] Follow up with Karen for the skill matrix research for Rishi to work on seperate 

#### Items for next week's agenda

- [ ] Follow up with Manju with her Usability Pilot testing 
- [ ] Finalize date time for researcher's availability for conduct testing
- [ ] Finalize the recruitment message
- [ ] Finalize date and time for recruitment

**Comment by xxl228** [comment]
## [8/23] Agenda and Notes

### Prework
- [ ] Add any prework here

### Roll Call
-Vivian
-Rishi

#### Recurring Items: Happens on the UXR meeting
 - [ ] Accountability and Support Check
    - [ ] Review assignments for each Researcher [UXR issues in progress](https://github.com/hackforla/CivicTechJobs/projects/1?card_filter_query=uxr)

#### New Items
- [ ] Write a Usability Test Recruitment message for Karen to use at onboarding. 
- [ ] Make a Calendley invite with Vivian's personal zoom 
- [ ] Send Karen the previous two messages with along with the screener 
- [ ] Make new agenda for next week

#### Task items from Team meeting to review
- [ ] continue with #532 
  - [ ] Carry forward the "New Items" that we did not get to look at today

#### FYI
-Manju notified me today that she is on a new job, want to take a break from CTJ for about 4 weeks-ish, she still wants to be on the project. 

#### Notes from meeting
- Karen updated Rishi and Vivian about the new skills matrix research ideas, will wait for her further instructions before we begin.
- Will discuss with Lu about doing a card sort along with the skills matrix validation research with the experienced volunteers. 

### New Task Items
- see new items

#### Items for next week's agenda

**Comment by xxl228** [comment]
[9/13] Agenda and Notes
Prework
 Add any prework here
Roll Call
-Vivian
-Rishi

Recurring Items: Happens on the UXR meeting
 Accountability and Support Check
 Review assignments for each Researcher [UXR issues in progress](https://github.com/hackforla/CivicTechJobs/projects/1?card_filter_query=uxr)
New Items
 

- [ ] Modified a Usability Test Recruitment message slack channel recruitment
- [ ] Send recruitment message in ui-ux channel on Monday 9/16, recruitment message posted in #532 
- [ ] Discuss skill matrix research and assigned responsibilities for issue #567 


Task items from Team meeting to review
 continue with https://github.com/hackforla/CivicTechJobs/issues/532
 Carry forward the "New Items" that we did not get to look at today


Notes from meeting

We discussed more details about the Usability Test. We decided to let participants sign up in Calendly without a meeting link. Rishi and Vivian will reach out to them individually to share detailed meeting information with them once they indicated interest. If we do not get enough volunteers in the next two weeks, we will reach out to project design leads for help for getting participants.

**Comment by xxl228** [comment]
[9/20] Agenda and Notes
Prework
Add any prework here
Roll Call
-Vivian
-Rishi

Recurring Items: Happens on the UXR meeting
Accountability and Support Check
Review assignments for each Researcher [UXR issues in progress](https://github.com/hackforla/CivicTechJobs/projects/1?card_filter_query=uxr)
New Items



- [ ]  Re-Send recruitment message in ui-ux channel on Monday 9/23, recruitment message posted in https://github.com/hackforla/CivicTechJobs/issues/532

 

- [ ] Discuss skill matrix research and assigned responsibilities for issue [Epic] Research for Skills Matrix Content Audit  #567

Task items from Team meeting to review
continue with https://github.com/hackforla/CivicTechJobs/issues/532

- [ ] Found discrepancy between WCAG documentation and McDocs about minimum accessibility standards, will double check and follow up.

Carry forward the "New Items" that we did not get to look at today

Notes from meeting

-Initially debriefed usability testing as a team, be ready for next week's testing. 
-Need to recruit more participants. 
-We discussed accessibility of the design. We wonder if the initial design has been checked for accessibility @kcoronel. If it has been done, was it by WCAG 2.0 level AA, as specified in MCdocs. In the most recent documentation from WCAG, it specifies as the following as the minimum requirement: "While certain laws, such as the Accessibility for Ontarians with Disabilities Act (AODA) and Section 508 of the U.S. Rehabilitation Act of 1973, require conformance with WCAG 2.0 Level
AA (which also requires conforming with the 2.0 Level A success criteria), the U.S. Department of
Justice has referenced WCAG 2.1 Level AA (at minimum) as the benchmark in its more recent ADA
enforcement actions." - The Must-Have WCAG Checklist

**Comment by kcoronel** [comment]
Hi Team, adding the following item for discussion for your Dev Meeting:

Please review the MVP Flow Desktop that the UI/UX Design team has created. It would be great to capture team feedback or any questions within the issue > https://github.com/hackforla/CivicTechJobs/issues/570

**Comment by xxl228** [comment]
## 9/27 Agenda and Notes

### Prework
- [ ] Add any prework here

### Roll Call
-Manju
-Rishi
-Vivian

#### Recurring Items: Happens on the UXR meeting
 - [ ] Accountability and Support Check
    - [ ] Review assignments for each Researcher [UXR issues in progress](https://github.com/orgs/hackforla/projects/37/views/5)

- [ ] See updates in #532 for usability test update
- [ ] See updates in #567 for the skill matrix project updates

#### New Items
- [ ]  
- [ ] Make new agenda for next week

#### Task items from Team meeting to review
- [ ] 
  - [ ] Carry forward the "New Items" that we did not get to look at today

#### FYI
-

#### Notes from meeting
- Usability Testing need more volunteers. Vivian will update the Calendley invite for two more weeks, repost the recruitment message on Monday, reach out to CoP leads for assistance. Rishi will reach out to people who missed appointments for rescheduling.  
-Ask Karen to help apply for a non-profit free account at UserTesting.com for the skill matrix project. This account will be very useful for HfLA, unless there is one already. If there is an existing account, please help us to use it. 

### New Task Items
-

**Comment by xxl228** [comment]
9/27 Agenda and Notes
Prework
 Add any prework here
Roll Call
-Rishi
-Vivian

Recurring Items: Happens on the UXR meeting
 Accountability and Support Check

 Review assignments for each Researcher [UXR issues in progress](https://github.com/orgs/hackforla/projects/37/views/5)
 See updates in https://github.com/hackforla/CivicTechJobs/issues/532 for usability test update

 See updates in [Epic] Research for Skills Matrix Content Audit  #567 for the skill matrix project updates

New Items
[ ]
 Make new agenda for next week
Task items from Team meeting to review

 Carry forward the "New Items" that we did not get to look at today
FYI
Notes from meeting
Usability Testing need more volunteers. Vivian will send recruitment message again with new dates on Oct 8. Rishi will send a message about card sort tool this coming week to CoP. Vivian created a new issue for Accessibility check. Rishi will create an outline for the accessibility test we will run and post it on the issue when it is completed.

**Comment by xxl228** [comment]
10/11 Agenda and Notes
Prework
Add any prework here

Roll Call
-Rishi
-Vivian

Recurring Items: Happens on the UXR meeting
Accountability and Support Check

Review assignments for each Researcher [UXR issues in progress](https://github.com/orgs/hackforla/projects/37/views/5)
See updates in https://github.com/hackforla/CivicTechJobs/issues/532 for usability test update

See updates in [Epic] Research for Skills Matrix Content Audit https://github.com/hackforla/CivicTechJobs/issues/567 for the skill matrix project updates

New Items
[ ]
Make new agenda for next week
Task items from Team meeting to review

Carry forward the "New Items" that we did not get to look at today
FYI
Notes from meeting
-Discussed the plan for testing accessibility, Rishi will update the testing plan, and we will proceed with testing next week. 
-Still need to recruit at least 1 more volunteer for the Usability Test. Plan to recruit one of the new designers. If not, will resend the usability test recruitment message to UX-UI channel after Oct 22 onboarding event. 
-Continue to investigate tools for the skill matrix.

**Comment by xxl228** [comment]
10/18 Agenda and Notes
Prework
Add any prework here

Roll Call
-Rishi
-Vivian

Recurring Items: Happens on the UXR meeting
Accountability and Support Check

Review assignments for each Researcher [UXR issues in progress](https://github.com/orgs/hackforla/projects/37/views/5)
See updates in https://github.com/hackforla/CivicTechJobs/issues/532 for usability test update

See updates in [Epic] Research for Skills Matrix Content Audit https://github.com/hackforla/CivicTechJobs/issues/567 for the skill matrix project updates

See updates about Accessibility test https://github.com/hackforla/CivicTechJobs/issues/594
New Items
[ ]
Make new agenda for next week
Task items from Team meeting to review

Carry forward the "New Items" that we did not get to look at today
FYI
Notes from meeting
-Will focus on the accessibility checks this coming week, based on the guideline Rishi created. Tasks will be divided between Vivian and Rishi.
-Vivian will post the in the Admin channel in the coming week about the questions for the application. 
-Vivian will post more hours to recruit participants for the usability test after Monday 10/22 onboarding event.

**Comment by xxl228** [comment]
11/1 Agenda and Notes
Prework
Add any prework here

Roll Call
-Rishi
-Vivian

Recurring Items: Happens on the UXR meeting
Accountability and Support Check

Review assignments for each Researcher [UXR issues in progress](https://github.com/orgs/hackforla/projects/37/views/5)
See updates in https://github.com/hackforla/CivicTechJobs/issues/532 for usability test update

See updates in [Epic] Research for Skills Matrix Content Audit https://github.com/hackforla/CivicTechJobs/issues/567 for the skill matrix project updates

See updates about Accessibility test https://github.com/hackforla/CivicTechJobs/issues/594
New Items
[ ]
Make new agenda for next week
Task items from Team meeting to review

Carry forward the "New Items" that we did not get to look at today
FYI
Notes from meeting
-Discussed accessibility checks for MVP1. Found some issues, will conduct more research on inactive state, details see issue. 
-Vivian followed up with Ryan Chase from the 311 project for the UserTesting.com access. Waiting for a reply.
-Vivian will post more hours to recruit participants for the usability test after Monday 11/4. We only need 1 more participant and hopefully we can get one.

**Comment by xxl228** [comment]
11/22 Agenda and Notes
Prework
Add any prework here

Roll Call
-Jialing
-Vivian

Recurring Items: Happens on the UXR meeting
Accountability and Support Check

Review assignments for each Researcher [UXR issues in progress](https://github.com/orgs/hackforla/projects/37/views/5)
See updates in https://github.com/hackforla/CivicTechJobs/issues/532 for usability test update

See updates in [Epic] Research for Skills Matrix Content Audit https://github.com/hackforla/CivicTechJobs/issues/567 for the skill matrix project updates

See updates about Accessibility test https://github.com/hackforla/CivicTechJobs/issues/594
New Items
[ ]
Make new agenda for next week
Task items from Team meeting to review

Carry forward the "New Items" that we did not get to look at today
FYI
Notes from meeting
-Discussed next steps to analyzing usability test data. 
-Will not meet on 11/29 and will meet again Dec 6. May continue to meet in December to complete the Usability Test report.

**Comment by kcoronel** [comment]
## August 27, 2025 Agenda and Notes

### Prework
- [ ] Add any prework here

### Roll Call
-

#### Recurring Items: Happens on the UXR meeting
 - [ ] Accountability and Support Check
    - [ ] Review assignments for each Researcher [UXR issues in progress](https://github.com/orgs/hackforla/projects/37/views/5)

#### New Items
- [ ] Introductions 
- [ ] Overview of Project 
- [ ] Overview of GitHub 
- [ ] Next Steps 
   - Scheduling a meeting
- [ ] Make new agenda for next week

#### Task items from Team meeting to review
- [ ] 
  - [ ] Carry forward the "New Items" that we did not get to look at today

#### FYI
-

#### Notes from meeting
- @xliu5899 to complete issue --> https://github.com/hackforla/CivicTechJobs/issues/711
- Xiao has been taken through Google Drive 
- Staging site: **https://stage.civictechjobs.org/** 
- @kcoronel to see when is a good time for Xiao to join a Design Team meeting 
- Usability testing tool (@kcoronel to share the research done by UXR team) // what tools does Hack for LA use for usability testing 
- https://github.com/hackforla/tdm-calculator/wiki/Research

### New Task Items
- 

#### Items for next week's agenda

**Comment by kcoronel** [comment]
## 2025-14-10 Agenda and Notes

### Prework
- [ ] Add any prework here

### Roll Call
- Xiao Liu 
- Karen Coronel

#### Recurring Items: Happens on the UXR meeting
 - [ ] Accountability and Support Check
    - [ ] Review assignments for each Researcher [UXR issues in progress](https://github.com/orgs/hackforla/projects/37/views/5)

#### New Items
- [ ] Discuss #717 - next steps? 
- [ ] Discuss #719 
- [ ] Make new agenda for next week

#### Task items from Team meeting to review
- [ ] 
  - [ ] Carry forward the "New Items" that we did not get to look at today

#### FYI
-

#### Notes from meeting
- 

### New Task Items
- 

#### Items for next week's agenda

**Comment by Rabia2219** [comment]
- https://github.com/hackforla/CivicTechJobs/issues/726
