### ISSUE TITLE
Development Roadmap to Production

### ISSUE THREAD

**Issue by Aveline-art** [hackforla/CivicTechJobs#249]
### Overview

As a developer, we need to outline our needs and goals in order to reach prod. This issue will serve as an epic for all development goals and milestones to reach prod mvp.

#### Backend todo:
  - [ ] Complete setting up backend #159 #220
    - [ ] Mock role data, if needed
    - [ ] Mock poster data, if needed 
    - [ ] Mock tech data, if needed
  - [ ] Get final decision on project level data
    - [ ] Mock project level data, if needed 
  - [ ] Create API endpoints for frontend

#### Frontend todo:
  - [ ] Landing page
  - [ ] Qualifier page pt1
  - [ ] Qualifier page pt2
  - [ ] Search page
 
#### DevOps todo:
  - [ ] Staging environment
    - [ ] Integration Test
    - [ ] Smoke Test
    - [ ] Manual/Inter-team Test
    - [ ] User Test
  - [ ] Production environment
    - [ ] Alpha release
    - [ ] Beta release 

### Resources/Instructions

[Resources](https://hackforla.github.io/CivicTechJobs/resources/)

**Comment by Aveline-art** [comment]
```mermaid
sequenceDiagram
    Alice->>John: Hello John, how are you?
    John-->>Alice: Great!
    Alice-)John: See you later!
```

**Comment by Aveline-art** [comment]
This is closed because sudden requirements had blocked us from making this achievable. There is no point in a roadmap if requirements are added suddenly out of no where.
