### ISSUE TITLE
Create and refine further milestones to reflect the work being done in the project

### ISSUE THREAD

**Issue by sdimran** [hackforla/CivicTechJobs#253]
### Overview

We want to edit our milestones so that we can better track the progress of each discipline within the project and how close we are to achieving our goal. We also want to utilize the Milestones for organizing our prioritized backlog column on the Kanban project board. Helping us to comply with HackforLA Kanban guidelines. 

### Action Items
- [x] Review OCS milestones as an example and see how we can leverage their structure for ourselves
- [x] Draft a list of new milestones and share it with the leads for Dev and Design 
- [x] Reorganize the tasks in MVP1 milestone better reflecting our scope of work
- [x] Reorganize the tasks in post MVP milestones 

### Resources/Instructions
[2024 Milestones and Labels](https://docs.google.com/spreadsheets/d/1nmxB4_RQFo8YZZdvnbLSX9FtyJ3oo9Z0ekaBg__NWDU/edit#gid=614593474)
[OCS Milestones](https://github.com/hackforla/open-community-survey/milestones)
[CTG Milestones](https://docs.google.com/spreadsheets/d/1xYUlIKsfE2-CeExIQ8i3oLD8pC7hjMTPM2YLSMFA8_s/edit#gid=0) 
[CTJ Milestones](https://docs.google.com/spreadsheets/u/4/d/1VcDLJnDA5CE7euzaZxOcqS3LLgyUFVLeqvdZx2sFGQk/edit#gid=477987515)

**Comment by sabheasley** [comment]
Hey @kcoronel please update your status on the following!

1. Progress 
2. Blockers 
3. Availability 
4. ETA

**Comment by kcoronel** [comment]
Progress - Meeting with Bonnie on next Wednesday 11/15 to finish our conversation re: milestones 
Blockers - None at this time
Availability - will have time to implement the changes agreed upon with Bonnie after next week's meeting 
ETA - hope to have this done before December/first week of December

**Comment by kcoronel** [comment]
Please provide update @kcoronel 
1. Progress 
2. Blockers 
3. Availability 
4. ETA

**Comment by kcoronel** [comment]
Please provide an update @kcoronel 

1. Progress 
2. Blockers 
3. Availability 
4. ETA

**Comment by kcoronel** [comment]
Ideas: 
Milestones 
Update labels with features

**Comment by kcoronel** [comment]
Added Milestones to this project board.
