### ISSUE TITLE
Survey all the teams in order to build an effective data model

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/CivicTechJobs#35]
### Overview
We need accurate information about each team's meetings so that we can design a system that will allow potential volunteers to filter the roles by teams that meet when its convenient for them.

### Action Items
- [ ] Create a template
   - [x] Draft template (https://github.com/hackforla/CivicTechJobs/issues/35#issuecomment-922543834)
   - [x] Add label for template (feature: project meeting check)
   - [ ] Add template to repository
- [x] List all teams under resources (with check boxes)
   - [ ] Make issue for each team to gather data about that team's meetings and get any corrections to what currently appears.  Use the template below

### Resources/Instructions

- [ ] [100 Automations](https://github.com/100Automations/website) https://github.com/100Automations/Website/issues/460
  - URL of the project's homepage on the HfLA website: https://www.hackforla.org/projects/100-automations
  - Meeting times:
    - Thursday 5:00 pm, 1 hour
    - Saturday 2:00 pm, 2 hours
- [x] [311 Data](https://github.com/hackforla/311-data) https://github.com/hackforla/311-data/issues/1129
  - URL of the project's homepage on the HfLA website: [https://www.hackforla.org/projects/311-data](https://www.hackforla.org/projects/311-data)
  - Meeting times:
    - Thu 7:30 pm, 1 hour, Management Meeting
    - Thu 6:30 pm, 1 hour, Team Meeting
    - Thu 6:00 pm, 30 min, Data science meeting
- [x] Access the Data https://github.com/hackforla/access-the-data/issues/71
  - URL of the project's homepage on the HfLA website: https://www.hackforla.org/projects/access-the-data
  - Meeting tines:
    - none currently specified
- [x] [BallotNav](https://github.com/hackforla/ballotnav) https://github.com/hackforla/ballotnav/issues/436
  - URL of the project's homepage on the HfLA website: https://www.hackforla.org/projects/ballot-nav
  - Meeting times:
    - Tue 6:00 pm, 1 hour
- [ ] [Brigade Organizer's Playbook](https://github.com/codeforamerica/brigade-playbook)
  - URL of the project's homepage on the HfLA website: https://www.hackforla.org/projects/brigade-organizers-playbook
  - Meeting times: 
    - Sat 11:00 am, 2 hour, Core Team (needs to be changed)
    - Tue 10:00 am, 1 hour, Core Team
- [ ] [Civic Tech Index](https://github.com/civictechindex/website) https://github.com/civictechindex/CTI-website-frontend/issues/879
  - URL of the project's homepage on the HfLA website: https://www.hackforla.org/projects/civic-tech-index
  - Meeting times: 
    - Thu 6:00 pm, 1 hour, Team Meeting
    - Mon 6:00 pm, 2 hour, Team Meeting
    - Wed 12:30 pm, 1 hour, Product Managers Meeting
- [ ] [Engage](https://github.com/hackla-engage) https://github.com/hackla-engage/start-here/issues/25
  - URL of the project's homepage on the HfLA website: https://www.hackforla.org/projects/engage
  - Meeting times: 
    - Tue 6:00 pm, 1 hour, All Team Members
    - Wed 5:00 pm, 1 hour, Product Manager Meeting
    - Sun 4:00 pm, 1 hour, All Team Members
- [x] [Expunge Assist](https://github.com/hackforla/record-clearance/) https://github.com/hackforla/expunge-assist/issues/340
  - URL of the project's homepage on the HfLA website: https://www.hackforla.org/projects/expunge-assist
  - Meeting times: 
    - Mon 6:00 pm, 1 hour, Team meeting on 1st & 3rd Mondays/PM on all other Mondays
    - Tue 6:00 pm, 1 hour, Research & Design meeting
    - Thu 6:00 pm, 1 hour, Dev meeting
- [ ] [Food Oasis](https://github.com/hackforla/food-oasis) https://github.com/hackforla/food-oasis/issues/1034
  - URL of the project's homepage on the HfLA website: https://www.hackforla.org/projects/food-oasis
  - Meeting times: 
    - Tue 6:30 pm, 1 hour, Development
    - Thu 6:00 pm, 1 hour, Team
    - Mon 3:00 pm, 1 hour, Management
- [ ] [GreenEarthOS](https://github.com/hackforla/climate-project) https://github.com/hackforla/GreenEarthOS/issues/77
  - URL of the project's homepage on the HfLA website: https://www.hackforla.org/projects/green-earth-os
  - Meeting times: 
    - Wed 7:00 pm, 1 hour, Team Meeting
- [x] [HomeUniteUs](https://github.com/hackforla/homeuniteus) https://github.com/hackforla/HomeUniteUs/issues/342
  - URL of the project's homepage on the HfLA website: https://www.hackforla.org/projects/home-unite-us
  - Meeting times: 
   - Product Management, Tuesday 6:00pm, 1 hour
   - All Team Meeting, Every Other Tuesday 7pm, 1 hour 
   - Design Meeting, Every Other Tuesday 7pm, 1 hour 
   - Product Owner Meeting, Friday 4pm, 1 hour

- [ ] [Lucky Parking](https://github.com/hackforla/lucky-parking) https://github.com/hackforla/lucky-parking/issues/303
  - URL of the project's homepage on the HfLA website: https://www.hackforla.org/projects/lucky-parking
  - Meeting times: 
    - Mon 6:00 pm, 1 hour, Team Meeting
- [x] [Open Community Survey](https://github.com/hackforla/open-community-survey) https://github.com/hackforla/open-community-survey/issues/45
  - URL of the project's homepage on the HfLA website: https://www.hackforla.org/projects/open-community-survey
  - Meeting times: 
    - Mon 12:00 pm, 1 hour, Team Meeting
- [ ] [TDM Calculator](https://github.com/hackforla/tdm-calculator) https://github.com/hackforla/tdm-calculator/issues/960
  - URL of the project's homepage on the HfLA website: https://www.hackforla.org/projects/tdm-calculator
  - Meeting times: 
    - Wed 7:00 pm, 1.5 hours
    - Sat 10:00 am, 2 hours
- [x] [VRMS](https://github.com/hackforla/VRMS) https://github.com/hackforla/VRMS/issues/768
  - URL of the project's homepage on the HfLA website: https://www.hackforla.org/projects/vrms
  - Meeting times: 
    - Mon 7:00 pm, 2 hour
    - Thu 6:30 pm , 1 hour, Developers' Meeting
- [ ] [HackforLA.org website](https://github.com/hackforla/website)
  - URL of the project's homepage on the HfLA website: https://www.hackforla.org/projects/website
  - Meeting times: 
    - Sun 10:00 am, 2 hours, All Team Meeting
    - Tue 7:00 pm, 1 hour, Development Team
    - Wed 12:00 pm, 1 hour, PM Meeting
    - Thu 5:00 pm, 1 hour, UI-UX Meeting
    - Thu 7:00 pm, 1 hour, Back-end Meeting
- [ ] [Youth Justice Nav](https://github.com/hackforla/YouthJusticeNav/)
  - URL of the project's homepage on the HfLA website: https://www.hackforla.org/projects/youthjusticenav
  - Meeting times: 
    - Wed 7:00 pm, 1 hour, Team Meeting
    - Fri 3:00 pm, 1 hour, Team Meeting
- [ ] [Design Systems](https://github.com/hackforla/design-systems) https://github.com/hackforla/design-systems/issues/105
  - URL of the project's homepage on the HfLA website:  none yet
  - Meeting times: 
    - none currently recorded 
- [ ] [Guides](https://github.com/hackforla/guides)
  - URL of the project's homepage on the HfLA website: https://github.com/hackforla/website/issues/2289
  - Meeting times (not currently on the website): 
    - Monday, 7:30 AM, 1hour, Meeting
    - Monday, 8:30 AM, 30 min, PM and Developer meeting
    - Wednesday, 8:30, 1hour, Meeting
    - Wednesday, 8:30 AM, 30 min, PM and Developer meeting
    - Friday, 8:30 AM, , 1hour, Meeting
    - Friday, 8:30 AM, 30 min, PM and Developer meeting
- [ ] [Internship](https://github.com/hackforla/internship)
  - URL of the project's homepage on the HfLA website: https://github.com/hackforla/website/issues/2288
  - Meeting times: 
    - none currently recorded
- [x] [Civic Tech Jobs](https://github.com/hackforla/CivicTechJobs)
  - URL of the project's homepage on the HfLA website: https://github.com/hackforla/website/issues/2287
  - Meeting times (not currently on the website): 
    - Tuesday 5pm, 1 hour, All team meeting
    - Sundays, 12pm, 1 hour, PM and management meeting
    - Sundays, 10am, 1 hour, PM meeting
    - Tuesday 6pm, 1 hour, Developers meeting
    - Tuesday 6pm, 1 hour, UI/UX Meeting
    - 
- [ ] [Data Science Projects](https://github.com/hackforla/data-science)
  - URL of the project's homepage on the HfLA website:  none yet
  - Meeting times: 
    - none currently recorded

**Comment by ExperimentsInHonesty** [comment]
```
### Overview 
The Civic Tech Jobs team needs accurate meeting time information to help match your project with available volunteers.

### Action Items
- [ ] Review the existing meeting times that VRMS and Hack for LA website have for your project (see resources below)
   - [ ] Indicate if any of the times or meeting names are inaccurate (need change)
   - [ ] indicate if any of the meetings are no longer happening (need deletion)
   - [ ] indicate if any meetings are missing from the list (need creation)
   - [ ] Separately, please provide more details about the each meeting by using a copy of the check boxes below

  - [ ] day
   - [ ] start_time
      - [ ] AM
      - [ ] PM
   - [ ] duration_in_min
   - [ ] name_of_meeting
   - [ ] who_must_attend
      - [ ] pm
      - [ ] all_leads
      - [ ] design_lead
      - [ ] research_lead
      - [ ] frontend lead
      - [ ] data_science_lead
      - [ ] design
      - [ ] research
      - [ ] frontend
      - [ ] data_science
      - [ ] other: please explain
   - [ ] who_should_attend
      - [ ] pm
      - [ ] all_leads
      - [ ] design_lead
      - [ ] research_lead
      - [ ] frontend lead
      - [ ] data_science_lead
      - [ ] design
      - [ ] research
      - [ ] frontend
      - [ ] data_science
      - [ ] other: please explain
   - [ ] who_can_attend
      - [ ] pm
      - [ ] all_leads
      - [ ] design_lead
      - [ ] research_lead
      - [ ] frontend lead
      - [ ] data_science_lead
      - [ ] design
      - [ ] research
      - [ ] frontend
      - [ ] data_science
      - [ ] other: please explain
```
### Resources
URL of the project's homepage on the HfLA website:  [INSERT PROJECT URL HERE]
Times that VRMS shows for your meetings: [INSERT PROJECT MEETING TIMES]

**Comment by Hanastevenson** [comment]
The Design Systems team have added their meeting times and completed their [Issue](https://github.com/hackforla/design-systems/issues/105).

Design Systems Weekly meeting. Monday 6:30pm, 1 hour
Design Systems UX/UI meeting.Tuesday 6:30pm 1 hour
Design Systems UX Research meeting. Tuesday 11am 1 hour

**Comment by gigicobos** [comment]
Food Oasis done: https://github.com/hackforla/food-oasis/issues/1034

**Comment by PLoiya** [comment]
GreenEarthOS updated their details : https://github.com/hackforla/GreenEarthOS/issues/77#issue-1005890743

**Comment by sharadgaurav7** [comment]
All meeting details of the Civic Tech Jobs teams: https://github.com/hackforla/CivicTechJobs/issues/38

**Comment by ExperimentsInHonesty** [comment]
311 has completed https://github.com/hackforla/311-data/issues/1129

**Comment by jonarcisse** [comment]
Open Community Survey has completed meeting details: https://github.com/hackforla/open-community-survey/issues/45

**Comment by drubgrubby** [comment]
VRMS complete: https://github.com/hackforla/VRMS/issues/768

**Comment by kcoronel** [comment]
BallotNav complete: [hackforla/ballotnav/issues/436#](https://github.com/hackforla/ballotnav/issues/436#issue-1005853156)

**Comment by simzou** [comment]
Lucky  Parking: https://github.com/hackforla/lucky-parking/issues/303#issuecomment-934005485

**Comment by ExperimentsInHonesty** [comment]
Open Community Survey complete https://github.com/hackforla/open-community-survey/issues/45

**Comment by kcoronel** [comment]
please note edit for BallotNav. meeting time changed from 5pm to 6pm.

**Comment by ExperimentsInHonesty** [comment]
Found this on my own personal drive.  Dumping it here in case we need it later
2021-09-19
Date, Start Time, Duration, Name of Meeting, Must Attend, Should, Can Attend
Sun, 10:00 am, 2 hr, All Team Meeting, [PM & All Leads], All, All
Tue, 12:00 pm, 1 hr, UI/UX Lead & PM meeting, [Research Lead, Design Lead, PMs], ,
Tue, 7:00 pm, 1 hr, Development Team, [Font End Lead, Back End Lead], [Back end developers, Front end developer], All
Wed, 12:00 pm, 1 hr, PM Meeting, PMs, ,
Thu 5:00 pm, 1 hr, UI-UX Meeting, [Research Lead. Design Lead], [Researchers, Designers], ???
Thu 7:00 pm, 1 hr, Back-end Meeting. Back End Lead, [Back End Developers, Front End Leads], All

**Comment by ExperimentsInHonesty** [comment]
Still working on this.  Check in with me next week

**Comment by henlatourrette** [comment]
100 Automations meeting times is updated: [100Automations/Website/issues/460](https://github.com/100Automations/Website/issues/460)

**Comment by ExperimentsInHonesty** [comment]
Green Earth OS is complete https://github.com/hackforla/GreenEarthOS/issues/77

**Comment by ExperimentsInHonesty** [comment]
Closing issue #11 which is related to this issue but not needed anymore.  Here are some links from that issue
[Team meeting spreadsheet
](https://docs.google.com/spreadsheets/d/1xG8yQUeR17mkeClJE5gotpWFoP8z6_rE53fqAWBMpOg/edit#gid=0)
[Events page schedule
](https://www.hackforla.org/events/)
[Upcoming Volunteer Opportunities page](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=5326%3A26395)

**Comment by ExperimentsInHonesty** [comment]
Add the milestone Content gathering to this issue

**Comment by ExperimentsInHonesty** [comment]
Home Unite US is done https://github.com/hackforla/HomeUniteUs/issues/342

**Comment by thomasdemoner** [comment]
Expunge Assist: https://github.com/hackforla/expunge-assist/issues/340

**Comment by smsada** [comment]
Civic Tech Index: [CTI-website-frontend/issues/879](https://github.com/civictechindex/CTI-website-frontend/issues/879)

**Comment by smsada** [comment]
Civic Tech Index: [CTI-website-frontend/issues/879](https://github.com/civictechindex/CTI-website-frontend/issues/879)

**Comment by kcoronel** [comment]
@ExperimentsInHonesty nudging you about closing this issue - I believe you needed to gather some info from VRMS

**Comment by kcoronel** [comment]
Hack for LA has gotten project teams to update their info on VRMS
