### ISSUE TITLE
Updating Product Roadmap for MVP

### ISSUE THREAD

**Issue by kcoronel** [hackforla/CivicTechJobs#354]
### Overview
After our requirements meeting with Bonnie #348, we decided to move forward with adding the CMS to our MVP. The reason for this, is that in the time it will take our developers to come up with an alternative solution only for the MVP, the time will be better suited in having developers focus on CMS. As a team, we need to agree on updated summary of our MVP and an updated timeline.

### Action Items
- [x] Speak with Design, Dev, and User Research leads about 
        - What does our MVP look like now, what features are a must, and what features are could have's 
        - How much time does each team need? (be sure to add buffers) 
- [x] Update product roadmap 
- [x] Update features list (if necessary)
