### ISSUE TITLE
Gather missing information for ticket to add Civic Tech jobs to HackforLA website

### ISSUE THREAD

**Issue by sdimran** [hackforla/CivicTechJobs#36]
### Dependency
- #~49~
- #~18~ 

### Not dependent, but highly recommended
If there is info that is not correct on this page, it will waste new volunteer time.  Its not hard to fill out the basic wiki, just get it done.
- #19 

### Overview
we need to gather additional information to complete the issue to add civic tech jobs to the hackforLA website so that there is more visibility for the project and users can get additional information about the project,

### Action Items 
- [x] Gather the following items
   - [x] Any resources for a Getting Started link (a link to a wiki, readme(s) or both):
      - [x] Wiki: #19 
      - [x] readme or contributing doc #49
      - [x] Overview (#18 ): [Completed PDF One Sheet ](https://github.com/hackforla/product-management/blob/master/project-one-sheets/Civic-Tech-Jobs-One-Sheet.pdf)
   - [x] link to hero image 1500x700 (https://drive.google.com/file/d/1fCbocnGqLuw2fkKeAi3Ke0UVFo3qXaqE/view?usp=sharing)
   - [x] link to logo on a image 600x400 (https://drive.google.com/file/d/17nWwqWpc4wA5atUMfN_EtJ6SUUwX_oar/view?usp=sharing)
   - [x] a blurb about the project (see following blurb below) 
  
 The CivicTechJobs.org MVP website will be a platform to help prospective volunteers find inter disciplinary projects that will be useful for their career development while contributing to positive civic impact and a CMS for Hack for LA projects to be able to list their open roles.
The tool will match volunteers by availability, role, and program area. Future iterations of the platform will focus helping volunteers find volunteer opportunities that match paid job postings, so that a volunteer can better prepare themselves for the marketplace.

- [x] ask bonnie to release the dependency on https://github.com/hackforla/website/issues/2287

### Resources

One sheet: https://github.com/hackforla/product-management/blob/master/project-one-sheets/Civic-Tech-Jobs-One-Sheet.pdf

**Comment by sdimran** [comment]
Reviewed and reworked One sheet blurb to better align with the current product vision and MVP. will be realigning with Sharad this week to iron out details before review

**Comment by sdimran** [comment]
https://drive.google.com/file/d/17nWwqWpc4wA5atUMfN_EtJ6SUUwX_oar/view?usp=sharing 

Link to the CTJ logo 600x400

**Comment by sdimran** [comment]
Blurb about CTJ (taken from one sheet)

The goal of CivicTechJobs is to give technology practitioners interested in having civic impact the tools and opportunity to find jobs or volunteer opportunities from a central hub of listings. The first phase of the project will focus on providing the potential volunteers a platform to find a project at HackforLA, connecting ambitious and like minded individuals together to help build digital products, programs, and services. For this phase, the website’s key features would include a list of open volunteer positions for projects undertaken by HackforLA and a self-filter option to find the best match for the volunteer’s skills, interest, and availability. The website will then guide the volunteer to the onboarding process to join the project of their interest.

Further down the line, our goal is to expand the horizon of CivicTechJobs so that we may act as an independent job board, housing both volunteer positions as well as paid positions for companies in the civic tech space to post and recruit through. Our volunteers will have the opportunity to learn, develop and apply their real-world knowledge with the confidence that the work that they have done has had a societal impact.

**Comment by ExperimentsInHonesty** [comment]
@sdimran @sharadgaurav7  Remaining task items are

- [ ] edit down this paragraph so that it makes sense on the hackforla website

> The goal of CivicTechJobs is to give technology practitioners interested in having civic impact the tools and opportunity to find jobs or volunteer opportunities from a central hub of listings. The first phase of the project will focus on providing the potential volunteers a platform to find a project at HackforLA, connecting ambitious and like minded individuals together to help build digital products, programs, and services. For this phase, the website’s key features would include a list of open volunteer positions for projects undertaken by HackforLA and a self-filter option to find the best match for the volunteer’s skills, interest, and availability. The website will then guide the volunteer to the onboarding process to join the project of their interest.

- [ ] finish one sheet

**Comment by sdimran** [comment]
> @sdimran @sharadgaurav7 Remaining task items are
> 
> * [ ]  edit down this paragraph so that it makes sense on the hackforla website
> 
> > The goal of CivicTechJobs is to give technology practitioners interested in having civic impact the tools and opportunity to find jobs or volunteer opportunities from a central hub of listings. The first phase of the project will focus on providing the potential volunteers a platform to find a project at HackforLA, connecting ambitious and like minded individuals together to help build digital products, programs, and services. For this phase, the website’s key features would include a list of open volunteer positions for projects undertaken by HackforLA and a self-filter option to find the best match for the volunteer’s skills, interest, and availability. The website will then guide the volunteer to the onboarding process to join the project of their interest.
> 
> * [ ]  finish one sheet

Please see below for the edited down paragraph for the hackforLA website: 

The goal of CivicTechJobs is to give technology practitioners interested in having civic impact the tools and opportunity to find jobs or volunteer opportunities from a central hub of listings. We want to provide a platform where ambitious volunteers can be connected with project teams to develop and refine their skillset in a welcoming space, better equipping them for their future career aspirations.

**Comment by ExperimentsInHonesty** [comment]
The CivicTechJobs.org MVP website will be a platform to help prospective volunteers find inter disciplinary projects that will be useful for their career development while contributing to positive civic impact and a CMS for projects to be able to list their project's open roles.

The tool will match volunteers by availability, role, and program area.  Future iterations of the platform will focus helping volunteers find volunteer opportunities that match paid job postings, so that a volunteer can better prepare themselves for the marketplace.

**Comment by sdimran** [comment]
@ExperimentsInHonesty awesome

I had omitted any mention of future iterations as I thought it would align better for the HackforLA website but if it is okay to include then great! I am happy with this. @sharadgaurav7 ?

**Comment by sharadgaurav7** [comment]
@sdimran , I'm good with it.

**Comment by ExperimentsInHonesty** [comment]
remaining items are

- One sheet link to pdf
- List of people on the project team
```
Name:
Role:
Slack ID:
GitHub handle:
```

**Comment by sdimran** [comment]
> remaining items are
> 
> * One sheet link to pdf
> * List of people on the project team
> 
> ```
> Name:
> Role:
> Slack ID:
> GitHub handle:
> ```
Hi @ExperimentsInHonesty , please see below for a list of all active team members for Civic Tech Jobs

Name: Syed Danish Imran
Role: Product Manager
Slack ID:U020Z27JB1S
GitHub handle: sdimran

Name: Sharad Gaurav
Role: Product Manager
Slack ID: U01RETBMLKS
GitHub handle:SharadGaurav7 

Name: Ava Li
Role: Full Stack Developer
Slack ID:U01B73XGCKV
GitHub handle: Aveline-art

Name: Sarah Williams
Role: Software Developer
Slack ID:U01S1S75NLW
GitHub handle: arghmatey

Name: Jen Chung
Role: UX/UI Designer
Slack ID:U02A6H5PVAA
GitHub handle: jenchuu

Name: Grace Lin
Role: UX/UI Designer
Slack ID:U02AE5H5BJ9
GitHub handle: graceerya

Name: Patty Costello
Role: UX Researcher
Slack ID:U01UTFC17L4
GitHub handle: patula006

Name: Stephanie G. Stahlberg
Role: UX Researcher
Slack ID:U02H06YBR7F
GitHub handle: stephaniestahlberg

Name: Helene Dendor
Role: UX Researcher
Slack ID:U02C41H7919
GitHub handle: dendorable

**Comment by ExperimentsInHonesty** [comment]
![Vertical Logo](https://user-images.githubusercontent.com/37763229/149637447-2d336d29-e615-44df-82e4-b92a8ade7455.png)

**Comment by ExperimentsInHonesty** [comment]
I have updated the issue https://github.com/hackforla/website/issues/2287, its ready for Ava to work on, if she likes

**Comment by sdimran** [comment]
@Aveline-art when we met with Bonnie over the weekend to finalize all the info for this task she had mentioned you were interested in taking this on. if this is still the case, it is ready to go and you can assign this to yourself and see the associated task on the HfLA website team board. please let me know if you have any questions

> I have updated the issue [hackforla/website#2287](https://github.com/hackforla/website/issues/2287), its ready for Ava to work on, if she likes

**Comment by Aveline-art** [comment]
@sdimran Thanks for getting back to me on this! I noticed that hackforla/website#2287 did not list technologies. Are we leaving that field empty for now? Also, the hero image does not have an alt text. Should I come up with one on my own or will the PM team handle it?

**Comment by sdimran** [comment]
@Aveline-art I saw in the issue itself there was no action item for alt hero image text or technologies but looking at the project.md template I do see the fields. 

for alt hero image text lets use a similar format to the logo alt text : 'Civic tech jobs hero image, for HfLA website projects page'. if you have any other suggestions or wording please let me know

for technologies lets include the stack we are working with (go ahead and add those details as you deem necessary from the developers perspective)

**Comment by Aveline-art** [comment]
@sdimran Below are screenshots of how the project card and page would appear once uploaded into the website. Let me know if they meet expectations :smile: ! For some of the images, especially the larger ones, you may need to scroll down to view the project.

[Project card desktop](https://user-images.githubusercontent.com/62368440/151217250-282ad5f8-74cc-4e8f-b491-efa1ae7477d5.png)
[Project card mobile](https://user-images.githubusercontent.com/62368440/151217487-b4900281-a0ef-412c-99d8-77784262ee76.png)


[Project page desktop](https://user-images.githubusercontent.com/62368440/151217676-b27355cc-e624-4f72-a287-90e2d53277cd.png)
[Project page mobile](https://user-images.githubusercontent.com/62368440/151217725-28a81979-4155-4507-92c9-4de59b30bf67.png)

**Comment by sdimran** [comment]
@Aveline-art  i think these look great! just a question and note:

Question: Regarding the project team profile pictures, are these automatically pulled and updated from github? if someone was to change theirs tomorrow would the site auto update or is this an ongoing maintenance item for us to update. 

note: with the upcoming additions to the team we will likely have to update the roster in the coming weeks, just a heads up that we may need to revisit the task.

This has my sign off

@sharadgaurav7 if you have a chance please take a look and give your sign off today as well so Ava can initiate the pull request and we can get the project on the website 👍🏽

**Comment by Aveline-art** [comment]
@sdimran Yes, the images are pulled automatically from our profiles, and retrieved when a user visits the website. Therefore, it is always the latest one.

**Comment by sharadgaurav7** [comment]
@sdimran @Aveline-art These look great. Thanks

**Comment by sdimran** [comment]
@Aveline-art you are good to continue with this with both of our sign off -- please let us know when it is live. we can review and then consider this done. Thanks!

**Comment by Aveline-art** [comment]
Hi! Our project is now live at [this link](https://www.hackforla.org/projects/civic-tech-jobs). It lacks our meeting times however, which I think is done [here](https://github.com/hackforla/VRMS/issues/new?assignees=&labels=1+week+change+request&template=add-edit-team-meeting-time.md&title=Meeting+time+change+request+for+%5BProject+Name%5D).

**Comment by sdimran** [comment]
Thanks Ava -- I missed this comment. i will submit that request

**Comment by Aveline-art** [comment]
@sdimran Is this issue done? Can I close it?

**Comment by sdimran** [comment]
yup we can close it -- i have created an issue on the VRMS board to have the team meetings added.
