### ISSUE TITLE
CTJ: DEV TEAM Meeting Agenda Tuesday 🏖️ 

### ISSUE THREAD

**Issue by Aveline-art** [hackforla/CivicTechJobs#39]
### Overview

This issue tracks the agenda for the CivicTechJobs team and weekly roll call.

### Action Items

- [ ] Designate a note taker 
- [ ] Make announcements
- [ ] Do below agenda items

### Weekly Agenda Markdown

```
### Agenda for monthAsText dd, yyyy

- [ ] writeYourNotesHere

### Post-meeting notes, monthAsText dd, yyyy

<details>
<summary>Title</summary>
<br>

insertNotesHere

<br>
</details>
```

<details>
<summary>Example Agenda</summary>
<h3> Agenda for November 9, 3012* </h3>

- [ ] Discuss when to have a meeting about making origami </input>
- [ ] Get feedback on 3 different brands of folding paper
- [ ] Create issue about the origami ship project

<h6><strong> *Note: Date is written out because of cultural differences in date formatting. </strong></h6>
</details>

**Comment by Aveline-art** [comment]
### Agenda for October 05, 2021

- [ ] Designate a note taker who will follow up on issue creation
- [ ] Pair program to set up docker, django, and react backend

**Comment by arghmatey** [comment]
### Notes for October 19, 2021

- Pair programming React into our Django project. Configured Babel and Webpack. 
- Discussed further configuration for Django calling onto React frontend. Script tag in Django template / or / through project urls.
- Agreed upon OnePassword being used as "secret collector", using a vault to keep sensitive information in.

**Comment by Aveline-art** [comment]
### Agenda for November 16, 2021

- [ ] Designate a note taker who will follow up on issue creation
- [ ] Meet with @sharadgaurav7 and @sdimran to discuss our MVP requirements and decide whether we need a backend at all

**Comment by Aveline-art** [comment]
### Agenda for November 30, 2021

- [ ] Designate a note taker who will follow up on issue creation
- [ ] Review [the data provided by the peopleDepot team](https://github.com/hackforla/CivicTechJobs/issues/13#issuecomment-982081532)
  - [ ] Based on that, create API wishlists, basically what is the input we give, and what output of data do we expect
  - [ ] Write the wishlists in a new issue [here](https://github.com/hackforla/peopledepot/issues)

**Comment by Aveline-art** [comment]
### Agenda for December 07, 2021

- [ ] Designate a note taker who will follow up on issue creation
- [ ] Discuss the parsing of issues outline [here](https://github.com/hackforla/CivicTechJobs/issues/47#issuecomment-983877110)
- [ ] Discuss whether there needs to be more issues for other components outside of the landing page
- [ ] Discuss the architecture for the frontend app

**Comment by Aveline-art** [comment]
### Agenda for December 14, 2021

- [ ] Designate a note taker who will follow up on issue creation
- [ ] Discuss architecture
  - [ ] Where do components go?
  - [ ] How do we subdivide css from js files?
  - [ ] Where do assets go?
  - [ ] Where do we combine components into a webpage?

**Comment by Aveline-art** [comment]
### Agenda for January 04, 2022

- [ ] Designate a note taker who will follow up on issue creation
- [ ] Happy New Year!
- [ ] Review #49, #75, #100, #103

**Comment by Aveline-art** [comment]
### Agenda for January 11, 2022

- [ ] Designate a note taker who will follow up on issue creation
- [ ] Get feedback on #75 if any

**Comment by Aveline-art** [comment]
### Agenda for February 1, 2022

- [ ] Designate a note taker who will follow up on issue creation
- [ ] To Prettier or not to Prettier?
- [ ] Eslint and stylelint configurations
- [ ] Should we add typescript to our stack? Is it needed? Is it useful?

**Comment by Aveline-art** [comment]
### Agenda for February 9, 2022

- [ ] Designate a note taker who will follow up on issue creation
- [ ] Revisit adding typescript to our stack

**Comment by Aveline-art** [comment]
### Agenda for February 15, 2022

- [ ] Designate a note taker who will follow up on issue creation
- [ ] Weekly check-in
  - [ ] What have I worked on this week?
  - [ ] What am I working on now?
  - [ ] What blockers do I have?
  - [ ] What do I plan to work on in the future?
- [ ]

**Comment by Aveline-art** [comment]
### Post-meeting notes, monthAsText dd, yyyy

<details>
<summary>Click for notes</summary>
<br>

insertNotesHere

<br>
</details>

**Comment by Aveline-art** [comment]
### Agenda for monthAsText dd, yyyy

- [ ] Designate a note taker who will follow up on issue creation
- [ ] Weekly check-in
  - [ ] What have I worked on this week?
  - [ ] What am I working on now?
  - [ ] What blockers do I have?
  - [ ] What do I plan to work on in the future?
- [ ] Check that the team have 2fa, see this [link](https://docs.google.com/presentation/d/1CVxhSjUbElQx83ZCrWBTBiz7qW7wmydPc99gJLmvejQ/edit#slide=id.p
), slide 4

**Comment by Aveline-art** [comment]
### Agenda for March 08, 2022

- [ ] Designate a note taker who will follow up on issue creation
- [ ] Weekly check-in
  - [ ] What have I worked on this week?
  - [ ] What am I working on now?
  - [ ] What blockers do I have?
  - [ ] What do I plan to work on in the future?
- [ ] First issue introspective
  - [ ] How did it feel to work on a difficult issue?
  - [ ] How can we work together to improve our delivery speed and accuracy?
  - [ ] What is the plan going forward?

**Comment by Aveline-art** [comment]
### Agenda for March 14, 2022

- [ ] Designate a note taker who will follow up on issue creation
- [ ] Weekly check-in
  - [ ] What have I worked on this week?
  - [ ] What am I working on now?
  - [ ] What blockers do I have?
  - [ ] What do I plan to work on in the future?

**Comment by Aveline-art** [comment]
### Agenda for March 29, 2022

- [ ] Designate a note taker who will follow up on issue creation
- [ ] Weekly check-in
  - [ ] What have I worked on this week?
  - [ ] What am I working on now?
  - [ ] What blockers do I have?
  - [ ] What do I plan to work on in the future?
- [ ] Discuss the staging environment

**Comment by Aveline-art** [comment]
### Agenda for April 05, 2022

- [ ] Designate a note taker who will follow up on issue creation
- [ ] Weekly check-in
  - [ ] What have I worked on this week?
  - [ ] What am I working on now?
  - [ ] What blockers do I have?
  - [ ] What do I plan to work on in the future?
- [ ] Rethinking the frontend directory
  - [ ] A lot of the django files in there serves no purpose
  - [ ] Most of the frontend files can/should be discarded after compiling everything into bundles
  - [ ] Should the frontend directory only be files needed to create the frontend and running webpack?
    - [ ] Where will static files be outputted? (candidate: server static) 
    - [ ] Will this interrupt backend development work in a significant way?
    - [ ] Should we hold off on this until we start to create our backend infrastructure?

**Comment by Aveline-art** [comment]
### Agenda for April 12, 2022

- [ ] Designate a note taker who will follow up on issue creation
- [ ] Weekly check-in
  - [ ] What have I worked on this week?
  - [ ] What am I working on now?
  - [ ] What blockers do I have?
  - [ ] What do I plan to work on in the future?

**Comment by Aveline-art** [comment]
### Agenda for April 19, 2022

- [ ] Designate a note taker who will follow up on issue creation
- [ ] Weekly check-in
  - [ ] What have I worked on this week?
  - [ ] What am I working on now?
  - [ ] What blockers do I have?
  - [ ] What do I plan to work on in the future?

**Comment by Aveline-art** [comment]
### Agenda for May 02, 2022

- [ ] Designate a note taker who will follow up on issue creation
- [ ] Weekly check-in
  - [ ] What have I worked on this week?
  - [ ] What am I working on now?
  - [ ] What blockers do I have?
  - [ ] What do I plan to work on in the future?
- [ ] Talk about testing architecture
  - [ ] Are we okay with the current directory structure, or should frontend be made its own on the root?
  - [ ] Will be interrupt staging environment work if we change architecture now?

**Comment by Aveline-art** [comment]
### Agenda for May 17, 2022

#### All-team Agenda

- [ ] Plan our dev roadmap for front + backend
- [ ] Backend todo:
  - [ ] Complete setting up backend #159 #220
    - [ ] Mock role data, if needed
    - [ ] Mock poster data, if needed 
    - [ ] Mock tech data, if needed
  - [ ] Create API endpoints for frontend
  - [ ] Get final decision on project level data
    - [ ] Mock project level data, if needed 
- [ ] Frontend todo:
  - [ ] Landing page
  - [ ] Qualifier page pt1
  - [ ] Qualifier page pt2
  - [ ] Search page
- [ ] DevOps todo:
  - [ ] Staging environment
    - [ ] Integration Test
    - [ ] Smoke Test
    - [ ] User Test
    - [ ] Manual Test
  - [ ] Production environment
    - [ ] Alpha release
    - [ ] Beta release 


#### Post-Agenda

- [ ] Designate a note taker who will follow up on issue creation
- [ ] Weekly check-in
  - [ ] What have I worked on this week?
  - [ ] What am I working on now?
  - [ ] What blockers do I have?
  - [ ] What do I plan to work on in the future?
- [ ]

**Comment by Aveline-art** [comment]
### Agenda for May 24, 2022

- [ ] Designate a note taker who will follow up on issue creation
- [ ] Weekly check-in
  - [ ] What have I worked on this week?
  - [ ] What am I working on now?
  - [ ] What blockers do I have?
  - [ ] What do I plan to work on in the future?

**Comment by Aveline-art** [comment]
### Agenda for July 05, 2022

- [ ] Designate a note taker who will follow up on issue creation
- [ ] Weekly check-in
  - [ ] What have I worked on this week?
  - [ ] What am I working on now?
  - [ ] What blockers do I have?
  - [ ] What do I plan to work on in the future?
- [ ] Typescript migration
- [ ] Merging dev-branch-1 into main
- [ ]  #267

**Comment by Aveline-art** [comment]
### Agenda for November 15, 2022

- [ ] Designate a note taker who will follow up on issue creation
- [ ] Weekly check-in
  - [ ] What have I worked on this week?
  - [ ] What am I working on now?
  - [ ] What blockers do I have?
  - [ ] What do I plan to work on in the future?
- [ ] Do we really need the domain, "staging.civictechjobs" 
  - [ ] If we just want to display the site, can we use the Amazon default url?
  - [ ] Pros? Cons?

**Comment by Aveline-art** [comment]
### Agenda for monthAsText dd, yyyy

- [ ] Designate a note taker who will follow up on issue creation
- [ ] Weekly check-in
  - [ ] What have I worked on this week?
  - [ ] What am I working on now?
  - [ ] What blockers do I have?
  - [ ] What do I plan to work on in the future?
- [ ] We need to having a coming soon page to host the civictechjobs domain
  - [ ] Should we purchase a test domain to get deployment out of the way?

**Comment by Aveline-art** [comment]
### Agenda for May 02, 2023

- [ ] Designate a note taker who will follow up on issue creation
- [ ] Weekly check-in
  - [ ] What have I worked on this week?
  - [ ] What am I working on now?
  - [ ] What blockers do I have?
  - [ ] What do I plan to work on in the future?
- [ ] Goals for the month
  - [ ] Complete the search results page
  - [ ] Complete deployment (stretch goal)
  - [ ] Separate frontend and backend code (stretch goal)

**Comment by kcoronel** [comment]
Closed due to team choosing to start a new agenda issue as new leads have stepped into the role.
