### ISSUE TITLE
Roadmap to Landing Page (Initial)

### ISSUE THREAD

**Issue by sharadgaurav7** [hackforla/CivicTechJobs#43]
### Overview

We need to define and list out tasks and dependencies to complete the MVP so that we can identify issues to make and that the team can understand the definition of done for the landing page MVP and follow up on the progress.

MVP: Fully developed front landing page with a clickable link to join Hack for LA in order to be eligible to see the list of open volunteer opportunities.  The link  leads to the meetup link for joining onboarding meeting. 

### List of Issues that need to be covered
- [ ] [Landing Page UX/UI Design](https://github.com/hackforla/CivicTechJobs/issues?q=is%3Aissue+label%3A%22p-feature%3A+Landing+Page%22++)
- [ ] [Copywriting](https://github.com/hackforla/CivicTechJobs/issues?q=is%3Aissue+label%3A%22role%3A+UI%2FUX+-+Research%22)
- [ ] Org sign off on copy writing and design
- [ ] Frontend and Backend Development
- [ ] Go Live

Resources:
[Civic Tech Jobs Roadmap](https://docs.google.com/spreadsheets/d/1VcDLJnDA5CE7euzaZxOcqS3LLgyUFVLeqvdZx2sFGQk/edit#gid=804221697)

#### Meetup link
https://meetup.com/hackforla/events

#### Examples
- Open Community Survey
   - OCS Roadmap issue: https://github.com/hackforla/open-community-survey/issues/43
   - [Open Community Survey Roadmap](https://docs.google.com/spreadsheets/d/163RPNWPhkeah2OvGCqjByMukYduXk66XY7ZpcpLCzXU/edit#gid=617281993)

**Comment by sdimran** [comment]
https://github.com/hackforla/website/wiki/How-to-read-and-interpret-labels#feature-series

including this link for reference to assist in label creation and organization

**Comment by sharadgaurav7** [comment]
Changed to milestone. Closing this issue
