### ISSUE TITLE
CTJ: Development Meeting Agenda

### ISSUE THREAD

**Issue by MattPereira** [hackforla/CivicTechJobs#450]
### Overview
A place to park ideas, concerns, or other discussion topics for development team 

2024: 
- 2024-31-01: https://github.com/hackforla/CivicTechJobs/issues/450#issuecomment-1920705795
- 2024-28-06: https://github.com/hackforla/CivicTechJobs/issues/450#issuecomment-2197701370
- 2024-16-08: https://github.com/hackforla/CivicTechJobs/issues/450#issuecomment-2294340311
- 2024-06-09: https://github.com/hackforla/CivicTechJobs/issues/450#issuecomment-2333070134
- 2024-19-09: https://github.com/hackforla/CivicTechJobs/issues/450#issuecomment-2362577809

**Comment by MattPereira** [comment]
### 2023-12-09

- [ ] How to reconcile conflicts between sass and tailwind
- [ ] Matt has concerns about if people depot's amazon cognito setup is viable for CTJ login -> see the docs

**Comment by kcoronel** [comment]
hi team @MattPereira @bzzz-coding are you using this issue as an agenda instead of #39

**Comment by MattPereira** [comment]
I didn't know about issue #39 because Ava never mentioned it and I failed to spot it in the `Links/Questions/Review` column of the all team project board

@kcoronel is there a specific issue you are experiencing with the MK Docs?

**Comment by kcoronel** [comment]
not a problem, do you want me to close #39? With MK Docs, I've updated this [doc section](https://github.com/hackforla/CivicTechJobs/blob/main/mkdocs/docs/joining-the-team/intro.md) (I need to update it again) but this current version doesn't show up on the [front-end](https://hackforla.github.io/CivicTechJobs/joining-the-team/intro/)

**Comment by MattPereira** [comment]
@kcoronel #39 is closed and yeah looks like the mkdocs deployment is indeed failing. We will do our best to fix it


https://github.com/hackforla/CivicTechJobs/actions/runs/6002157713/job/16277931316#step:4:138
![image](https://github.com/hackforla/CivicTechJobs/assets/73561520/05bb1c73-cb7f-4c56-b312-63ce40227bef)

**Comment by kcoronel** [comment]
FYI added this issue to our CTJ general project board as well :) - let me know if you have any questions

**Comment by MattPereira** [comment]
## 2023-10-18

- AWS deployment failing
  - https://github.com/hackforla/CivicTechJobs/actions/runs/6518963880/job/17704947779
  - https://stage.civictechjobs.org/
- MKdocs deployment failing
  - https://github.com/hackforla/CivicTechJobs/issues/456

**Comment by JimmyJuarez10** [comment]
### 2024-01-31

- Talked a about fix regarding MkDocs build 
   - https://github.com/hackforla/CivicTechJobs/issues/456
- Go over high level sketch of what the E2E flow should look like from Dev perspective
<img width="1479" alt="Screenshot 2024-01-31 at 11 51 57 PM" src="https://github.com/hackforla/CivicTechJobs/assets/41131371/16ed5333-a4ce-4c70-9f3f-9b4f5f5f8491">
- Planning to switch backend from Django to Express.js since that is what the team is more familar, need to talk to project manager to see if thats okay.
- Gave benny directive to look into vite for building our frontend.

**Comment by JimmyJuarez10** [comment]
### 06-28-2024

Issues worked on this Week:
- Bitian: Submitted this pull request https://github.com/hackforla/CivicTechJobs/pull/547
- Benny: Submit this pull request https://github.com/hackforla/CivicTechJobs/pull/545
- Jimmy: Reviewed Benny and Bitian's pull request and is working on adding the djangorestframework.

Issues we will work on next Week: 
-

**Comment by kcoronel** [comment]
### 08-16-2024

Issues worked on this Week: 
- Live troubleshooting of issue [add issue here] 

Issues we will work on next Week: 
- 

Product Team Questions: 
- Front end developers selections 
   - onboarding and first issues; Terrence Lo, Roja Pinnamraju, Anahis Valenzuela, Alejandro Martinez (okay with not being lead) 
[Terence_Lo_Resume.pdf](https://github.com/user-attachments/files/16641855/Terence_Lo_Resume.pdf)[Pinnamraju_Resume.pdf](https://github.co
[Anahis-Valenzuela-Resume-Civic-Tech-Jobs.pdf](https://github.com/user-attachments/files/16641863/Anahis-Valenzuela-Resume-Civic-Tech-Jobs.pdf)
m/user-attachments/files/16641854/Pinnamraju_Resume.pdf)
[Alejandro Martinez](https://www.linkedin.com/in/alejandro-martinez-jr/details/experience/)

1. What kinds of projects will I be working on?
_You will be working on transferring our ux designs into the front end for our product while the backend devs work on getting the backend setup._
3. Will these projects be collaborative team efforts, or more individual contributions?
_A mix of both. We will expect weekly team meetings for you to collaborate through any blockers or challenges but you will be assigned to your own piece of work via issues._
5. I noticed the role involves working with React frameworks. Will volunteers also have opportunities to work with other technologies, such as Express and Node? I am totally fine working on more Frontend/React work just curious what technologies volunteers work with.
_For frontend we only expect to use React._

1. How many people are working on the team currently? What is the balance between developers and designers?
Currently we have 2 backend devs and 2 designers. The designs are mostly 80% of the way there. 
3. How many hours do you expect a developer to work on this project per week?
I think at the beginning around 1-2 hours a week if we keep the team to 4 front end developers. 

- Offboarding Benny 
   - do we want to find another back-end developer? 

- Please review issues currently assigned to you and close issues appropriately. Nooria will be following up with you Jimmy to grab some time to clean up the board.

**Comment by JimmyJuarez10** [comment]
09-06-2024
Issues worked on this Week:

Anahis: Spoke with Terence for reorganizing the skills matrix. 
Terence: Reviewed Django Demo Walkthrough and submitted #564 for review.
Jimmy: Meeting with Karen and leads
Roja: N/A

**Comment by JimmyJuarez10** [comment]
09-19-2024
Issues worked on this past week:
- [X] Terence: Submitted a couple of PRs
1. #572 
2. #571 

- [X] Roja 
- [X] Kevin
- [X] Jimmy

Issues we will work on next week:

**Comment by kcoronel** [comment]
Hi Team, adding the following item for discussion for your Dev Meeting: 
- Please review the MVP Flow Desktop that the UI/UX Design team has created. It would be great to capture team feedback or any questions within the issue > https://github.com/hackforla/CivicTechJobs/issues/570

**Comment by LoTerence** [comment]
09-26-2024

Agenda

- [ ] Brief Team intros
Questions:
Where are you from?
What techs and tools do you like the most?
What experience do you have?
What made you join HFLA?

- [ ] What was done last week - Was everyone able to get a development environment running on their local machine?

- [ ] Talk about current issues and state of the project:

- Everyone is new and joined within the last month, so no one on the team really knows anything about the state of the project.
  - Documentation is severely outdated.
  - The main branch is not in sync with the develop branch, which is why the old installation instructions were out of date.

- There is no deployment at all at the moment.
  - This is why I brought Ryan in to help with that.
  - As far as I know, there was never a successful deployment

- Status of the frontend is unknown. Frontend needs a total audit.
- Backend is basically brand new at the moment.
  - Jimmy reset the backend completely, decoupling the `develop` branch from the `main` branch. The challenge will be to merge them back together as a team
  - We probably need a couple more backend devs. I'll sync with Karen on recruiting some


Issues we should address by next week:

Frontend
- [ ] [Frontend Audit · Issue #586 · hackforla/CivicTechJobs · GitHub](https://github.com/hackforla/CivicTechJobs/issues/586)

Review Lu's MVP flow:
- [ ] [Gather team feedback · Issue #581 · hackforla/CivicTechJobs · GitHub](https://github.com/hackforla/CivicTechJobs/issues/581)
- [ ] [MVP Flow (Desktop) #570](https://github.com/hackforla/CivicTechJobs/issues/570)

Devops
- [ ] [Fix GitHub Action Issue Trigger · Issue #579 · hackforla/CivicTechJobs · GitHub](https://github.com/hackforla/CivicTechJobs/issues/579)
- [ ] [Epic (Devops): Deploy develop Branch to Staging Environment in AWS](https://github.com/hackforla/CivicTechJobs/issues/585)

Terence
- [ ] [Fix mkdocs deployment](https://github.com/hackforla/CivicTechJobs/issues/456) 
- [ ] update dev onbarding documentation

**Comment by LoTerence** [comment]
We have this up: https://stage.civictechjobs.org/
But no one has any information about it

**Comment by kcoronel** [comment]
Terrence and Karen Chat on September 30, 2024 
- Team Lead Overview and Responsibility
- Overseeing the dev team, attending lead meetings,  delegating work

Karen to do: 
- Team Lead meeting - add Terrence - we will discuss decisions we have made for the project and how to document this on the wiki + prioritization of work 
- Clear requirements 
- Invite Terence to meeting with Bonnie 
- Sunday morning send Terence MVP doc we will share with Bonnie 
- Share with Bonnie ahead of PM/Org Meeting

**Comment by LoTerence** [comment]
10/03/2024

- [ ] Roja
- [ ] Kevin
- [ ] Ida
- [ ] Ryan
- [ ] Bitian
- [ ] Terence

Current Issues and state of project

- [ ] project lead expectations
- [ ] prioritize growth of developers
- [ ] rough plan
- [ ] review Lu MVP flow together

Rough plan:
1. stabilize the project
2. deploy staging asap
	1. The challenge is to have these two goals completed by the time the final designs come out
3. develop and deploy MVP-1

**Comment by RSkuma** [comment]
(10/3/2024) Questions Regarding CivicTechJobs Design/Vision that came up during team meeting: 

1. What is the main use for CTJ, a public facing recruitment site or an internal job board? Or Both? Or something else?

2a. What will CTJ's role in the onboarding process be? Will it be an additional step added to the current onboarding process? 
2b. Or will it be a replacement or augment to the current onboarding process? If so, will it be working with existing systems like tables and people depot or will it be replacing them?

3a. What should CTJ do for hfla members(volunteers who can login), what can they see and do? 
3b. What should CTJ do for non-members(visitors who can't login), what can they see and do?

4. How do project leads post positions on CTJ? There is no workflow or mockup on Figma for that yet

5. What are the core functions of CTJ that should be a part of MVP-1? What functions are secondary and can be added later?

**Comment by ExperimentsInHonesty** [comment]
@JimmyJuarez10 I am adding this to your agenda issue so that you can discuss at your next dev meeting.  

I got this message from @RSkuma 

> I was at the CivicTechJobs meeting to help with their deployment, but I wasn't able to get a complete picture of where they are at and was hoping you could help
> CivicTechJobs currently has some assets on the Incubator AWS account, but at the meeting they said they are planning to migrate to Incubator in the near future. If that's true, where are the AWS resources currently on Incubator from? Are they already on Incubator? Is it an older version? Or a partial deployment?
>  2. Will CivicTechJobs be deployed on Incubator permanently? Or is it temporary with the intent to grant them their own AWS account later?
>  3. Does CivicTechJobs already have their own AWS account? Somebody on the CivicTechJobs team said they did, and that their account is being charged $200 a month. I'm thinking they were logged into Incubator when they saw that number but I would like to confirm

Can you clarify what y'all know and what you need help?  And where we should communicate with you. I see this issue https://github.com/hackforla/CivicTechJobs/issues/585, but you also have these issues
[label:"feature: Architecture" aws](https://github.com/hackforla/CivicTechJobs/issues?q=is%3Aissue+is%3Aclosed+label%3A%22feature%3A+Architecture%22+aws)

**Comment by LoTerence** [comment]
10/17/2024

- [ ] Roja
- [ ] Kevin
- [ ] Ida
- [ ] Ryan
- [ ] Bitian
- [ ] Terence

Agenda
- [ ] Design team questions (search results page, dev handoff up to date, design system final components)
- [ ]

**Comment by LoTerence** [comment]
10/24/2024

- [ ] Roja
- [ ] Ida
- [ ] Ryan - not present
- [ ] Bitian - not present
- [ ] Terence

Agenda
- [ ] Backend - Created DB schema model
- [ ] Frontend - any updates about sass+tailwind story

Bitian - github action story
- should be ready to close

**Comment by LoTerence** [comment]
11/17/2024

- [ } Roja
- [x] Ida - not present
- [ ] Bitian
- [ ] Ryan
- [ ] Terence

Ida - Frontend
- Completed eslint story 🙌
- She will work on resolving all eslint errors next - issue 609

Agenda
- [ ] December break

Backend
- Created a new DB schema diagram
- Currently working on merging `develop` into `main` 
- Aim to deploy a staging environment by next week.
- Aim to develop API server by the end of the month

**Comment by LoTerence** [comment]
11/14/2024

- [ ] Bitian
- [ ] Roja - not present
- [ ] Ida - not present
- [ ] Ryan
- [ ] Terence

**Comment by LoTerence** [comment]
11/21/2024

- [ ] Roja
- [ ] Ida
- [ ] Bitian
- [ ] Ryan
- [ ] Terence

Karen needs to know:
- [ ] Our dev meeting schedule in December. What do you guys wanna do? Karen needs to know
- [ ] What is a good first day to meet in January?

Agenda
- [ ] Next week dev meeting is on thanksgiving. Lets move it to another day?
- [ ] Our roadmap progress: https://docs.google.com/document/d/1KTElKAprzv46-FqIBBcT5w8fi1oh6b03nCQfvm13XGE

Bitian
- 

Ryan
- 

Terence
-

**Comment by LoTerence** [comment]
12/12/2024

- [ ] Bitian
- [ ] Ryan
- [ ] Terence

Agenda

- Last meeting this month. Meet again January 9th 2025
- Ask Bitian if her dev env works - `CustomUser` is causing issues with the django migration and everyone might need to reset their docker environments from scratch

Bitian


Ryan

Terence
- Wrote docs about different branches, github branching flow
- mkdocs deploys from the `main` branch now
-

**Comment by LoTerence** [comment]
01/09/2025

- [ ] Bitian
- [ ] Ryan
- [ ] Terence
- [ ] Ida

Agenda

- 
- 

Terence
- Touch base with Design team to see what progress they are on for the qualifiers pages.
- What exactly is changing in the qualifiers pages? So we know what to expect
- Is the design system changing - individual components - eg buttons, colors, etc. before we migrate from sass to tailwind. We can prioritize which components to migrate to tailwind depending on what they want to change or keep the same.
-

**Comment by LoTerence** [comment]
01/16/2025

- [ ] Bitian
- [ ] Ryan
- [x] Ida
- [ ] Roja
- [ ] Terence

Agenda

- Go over roadmap, prioritize tasks
- Everyone able to start their dev environments?
- Any blockers?

Terence
- Finished documenting backend architecture, dev environment, stage environment, python linter.
- Had meeting with Leads
    - PM: Karen, Nooria and I to work on timeline for MVP-1.
    - PM: Karen can elevate deployment priorities to Bonnie if necessary.
    - Design: Lu to update us about a date when Qualifiers page designs will be finalized after her meeting this Friday. Current status is they finished this round of user testing, Lu needs to redesign and possibly do another round of user testing. So I expect it to be ready within a month.
    - Design: Design system has been reorganized and is up to date. We can migrate most components to tailwind without issue. More details here: https://github.com/hackforla/CivicTechJobs/issues/606
    - Question: What exactly is changing in the qualifiers pages?
        - Its going to be three pages: (1) Select CoP and Role. (2) Select skills aka skills matrix. (3) Availability Calendar.
        - Design team is working specifically on the skills matrix page right now.

Bitian
- 

Ryan
- 

Ida
- worked on eslint errors


Roja
-

**Comment by LoTerence** [comment]
01/23/2025

- [ ] Bitian
- [ ] Ryan
- [ ] Ida
- [ ] Roja
- [ ] Terence

Agenda

- Lu and Rishi want to meet up with the dev team to ask questions about the design. What time are you all free to do it this coming week?
- Go over roadmap, prioritize tasks
- Any blockers?


Terence
- 

Bitian
- 

Ryan
- 

Ida
- 

Roja
-

**Comment by LoTerence** [comment]
02/13/2025

- [ ] Bitian
- [ ] Ryan
- [ ] Terence


Terence


Bitian


Ryan

**Comment by LoTerence** [comment]
02/24/2025

- [ ] Bitian
- [ ] Ryan
- [ ] Terence

Ryan
- finished first wave of incubator deployment
- can start working on developing our actions
- there are some devops bugs

Terence
- 

Bitian
-

**Comment by LoTerence** [comment]
03/03/2025

- [ ] Bitian
- [ ] Ryan
- [ ] Terence

Ryan
- 

Terence
- 

Bitian
-

**Comment by LoTerence** [comment]
03/10/2025

- [ ] Bitian
- [ ] Ryan
- [ ] Terence

Bitian
- 

Ryan
- 

Terence
- Worked on FooterNav component
- Bitian - do you want to try reviewing PRs?
- Terence sent lines 35-37 in the deploy-dev to Ryan (Docker push commands for our app)

Leads meeting update
- Karen and Janis want to demo staging environment to Bonnie on 03/17
- Design Team will have new skills Matrix pages ready this week
- Ideally I would like to make a first draft of the Skills Matrix to show to Bonnie

**Comment by LoTerence** [comment]
03/17/2025

- [x] Bitian
- [x] Ryan
- [x] Terence
- [x] Benny

Figma Design System:
- https://www.figma.com/design/G5bOqhud6azbxyR9El9Ygp/Civic-Tech-Jobs?node-id=12290-2067&t=JljYtCAWoGMOghuK-0

Bitian
- Checkbox - confusion about Rishi's Checkbox design
- This week: keep working on Checkbox component

Ryan
- Moved all our AWS resources onto incubator repo
- https://civictechjobs-stage.vrms.io/
- There are DNS issues in AWS - which is why we have vrms domain for now. Devops is working on it. It will stay like this for a while.
- CI/CD pipeline is up and stable
- Look into setting up a testing pipeline

Terence
- Write issues for devs to work on. 
- Write issues splitting up the new Skills Matrix pages
- This week: Work on Qualifier context + Skill Eval routing

Benny
- convert Dialog component to Tailwind
- https://github.com/hackforla/CivicTechJobs/pull/647
- https://github.com/hackforla/CivicTechJobs/issues/583

**Comment by LoTerence** [comment]
03/24/2025

- [ ] Bitian
- [ ] Ryan
- [ ] Benny
- [ ] Terence

Agenda
- Terence cannot make it to meeting next monday, lets skip that meeting

Bitian
- 

Ryan
- 


Benny
- 

Terence
- I'm going to pivot to doing only PM tasks for now
- Organize the project board

**Comment by LoTerence** [comment]
04/07/2025

- [ ] Bitian
- [ ] Ryan
- [ ] Benny
- [ ] Terence

Agenda
- 

Bitian
- 

Ryan
- 

Benny
- 

Terence
-

**Comment by LoTerence** [comment]
04/14/2025

- [ ] Bitian
- [ ] Ryan
- [ ] Benny
- [ ] Terence

Agenda
- 

Bitian
- 

Benny
- 

Ryan
- 

Terence
- I let Karen and Janis know to find a new Dev Lead by end of the month. I will help them write the job posting
- Reviewed Bitian PR
- Reviewed Benny skills matrix PR
- Wrote a bunch of new tickets of things that should be done
- I will work on the frontend unit testing ticket

**Comment by LoTerence** [comment]
04/21/2025

- [ ] Bitian
- [ ] Ryan
- [ ] Benny
- [ ] Snigdha
- [ ] Terence

Agenda
- Ice breaker - Where are you from? What kind of programming work do you do? What do you like to do to relax/ what are you passionate about outside of work?

Bitian
- 

Benny
- 

Ryan
- 

Terence
- Opened PR for frontend unit tests - vitest
- Organize a dev team hangout in East LA - CTJ committee

**Comment by LoTerence** [comment]
04/28/2025

- [ ] Ryan
- [ ] Bitian
- [ ] Benny
- [ ] Snigdha
- [ ] Terence

Agenda
- 

Ryan
- 

Bitian
- 

Benny
- 

Terence
-

**Comment by snigdhat1** [comment]
04/28/2025

- [x] Ryan
- [x] Bitian
- [x] Benny
- [x] Snigdha
- [x] Jason

Agenda
- Qualifier pages - role does not effect what skills are surveyed
- Skills matrix spreadsheet (source of truth): https://docs.google.com/spreadsheets/d/1_sCd8Kc2Tlhe--8UJLkgyDoqyQw_eZxhie3QTOwTHrM/edit

Ryan
- 

Bitian
- refactoring tailwind checkbox component - approved and merged

Benny


Snigdha
- go through prs
- ask ryan if he is working on rds instance
- check user flow: https://www.figma.com/design/G5bOqhud6azbxyR9El9Ygp/Civic-Tech-Jobs?node-id=11626-3114&t=SzScd0eHSuHckYGZ-0

Jason

**Comment by snigdhat1** [comment]
05/12/2025


Ryan

Bitian

Benny

Snigdha

Jason

Agenda
Leads Meeting
- design team still working to finalize the new design
- pm team - new skills matrix not finalized yet

what are next steps since design is not finalized 
- database -> get data in database


Ryan

Bitian
- opened pr for new tw component

Benny

Snigdha

Jason

upcoming
- look into dev roadmap

**Comment by RSkuma** [comment]
05/19/2025

- [x] Ryan
- [x] Bitian
- [x] Benny
- [x] Snigdha
- [ ] Jason
- [ ] Gowthamii


**Agenda**
_PM Meeting with Bonnie_
- Discussed skills matrix documents and MVP-1 vs MVP-2 features
what are next steps since design is not finalized 
- database -> get data in database


Ryan

Bitian

Benny

Snigdha

Jason

**upcoming**

**Comment by snigdhat1** [comment]
05/19/2025

- [x] Ryan
- [] Bitian
- [] Benny
- [x] Snigdha
- [ x] Jason
- [x] Gowthamii


**Agenda**
- qualifier page - lu will finalize this week
- went through ctj dev roadmap with jason

Ryan
- doc for infra done (snigdha will check)

Bitian

Benny

Snigdha

Jason

Gowthamii
- got dev env setup and got onboarding tasks done

**upcoming**
- jason is making a dev roadmap

**Comment by snigdhat1** [comment]
06/09/2025

- [x] Ryan
- [x] Bitian
- [] Benny
- [x] Snigdha
- [] Jason
- [x] Gowthamii


**Agenda**
- updated team on new tickets for the log in, credits, privacy policy, and how to join us page
- snigdha to talk to people depot and karen to ask whether we should use the people depot api for the login page
- if people depot is not ready, we can create our own table to mimic the user table to test the login page


Ryan

Bitian

Benny

Snigdha

Jason

Gowthamii


**upcoming**

**Comment by snigdhat1** [comment]
06/16/2025

- [] Ryan
- [x] Bitian
- [] Benny
- [x] Snigdha
- [] Jason
- [] Gowthamii


**Agenda**
- snigdha to talk to people depot in their thursday meeting to figure out if we can use their api (if its done) 
- if people depot is not ready, we can create our own table to mimic the user table to test the login page

Ryan

Bitian
- continue working on https://github.com/orgs/hackforla/projects/37/views/1?pane=issue&itemId=114452955&issue=hackforla%7CCivicTechJobs%7C697
- will put up pr and pick up another task
- 
Benny

Snigdha
- work on showing coming soon page for civictechjobs.org

Jason

Gowthamii
- currently working on https://github.com/orgs/hackforla/projects/37/views/1?pane=issue&itemId=114482595&issue=hackforla%7CCivicTechJobs%7C700
- will put up pr for this


**upcoming**

**Comment by snigdhat1** [comment]
06/30/2025

- [x] Ryan
- [x] Bitian
- [ ] Benny
- [x] Snigdha
- [ ] Jason
- [x] Gowthamii

Agenda
- updates on tickets

Ryan
- going to work on linter

Bitian
- working on how to join us FAQ component

Snigdha
- pr reviws

Jason

Gowthamii
- working on How to join us page

upcoming

**Comment by RSkuma** [comment]
08/11/2025

- [x] Ryan
- [x] Bitian
- [ ] Benny
- [x] Snigdha
- [ ] Gowthamii

Agenda
- updates on active roster
- Plan for coming month
- Review Jason's Roadmap

Ryan


Bitian
- ask lu about issue #704 


Snigdha
- meet with people depot to make sure the table is the same based on the erd diagram.


Gowthamii
- on vacation till 8/19

**Comment by snigdhat1** [comment]
08/18/2025

- [x] Ryan
- [x] Bitian
- [ ] Benny
- [x] Snigdha
- [ ] Gowthamii

Agenda
- accessibility engineer -> put this in phase 5 since we have other priorities before this
Bonnie shared need for Accessibility Engineer; send someone from team and Ryan (TDM) would train them to do it and train others across projects. Can master and then make issues to train the team to be able to fix our own accessibility issues.

- updates on people depot api
- Jason was able to reply to the questions we had about the roadmap

Ryan
- helping lu get designers

Bitian

Snigdha
- meet with people depot to make sure the table is the same based on the erd diagram.
- make dev to main pr
- make issue to link backend to people depot user api
- make issue for backend documentation


Gowthamii
- on vacation 

Links:
people depot api schema: https://peopledepot-dev.vrms.io/api/schema/redoc/#tag/v1/operation/v1_users_retrieve
roadmap: https://docs.google.com/document/d/17yraNdhuH4p3NGCFSgWtMOYX5rMC67jhZO1PWYi5ZCw/edit?tab=t.0

**Comment by RSkuma** [comment]
08/25/2025

- [x] Ryan
- [x] Bitian
- [ ] Benny
- [ ] Snigdha
- [x] Gowthamii

Agenda


Ryan


Bitian
- Fixing Javascript exceptions when  from old code(Written by Ava several years ago)

Snigdha


Gowthamii
- Will be restarting Join Us page task which was kicked off of due to vacation

Links:

**Comment by snigdhat1** [comment]
09/29/2025

- [ ] Ryan
- [x] Bitian
- [ ] Benny
- [x] Snigdha
- [x] Gowthamii

Agenda
- update team on what next steps are for ctj

Ryan


Bitian
- working on https://github.com/orgs/hackforla/projects/37/views/1?pane=issue&itemId=107757006&issue=hackforla%7CCivicTechJobs%7C682
- there are a couple errors related to the login component that are out of scope for this ticket so we are skipping them and might create another ticket to address these if needed

Snigdha


Gowthamii
- finished how to join us page
- will work on updating saas to tailwind component ticket


Links:

**Comment by Rabia2219** [comment]
- https://github.com/hackforla/CivicTechJobs/issues/725
