### ISSUE TITLE
CRM Usability Test (Epic Issue)

### ISSUE THREAD

**Issue by jayywu** [hackforla/CivicTechJobs#453]
### Overview
This issue will outline the workflow for the usability test of CTJ's CRM job board. We will ask folks who participate to log in and post creation flow. This standard usability testing will be conducted with Community of Practice Leads and Product Managers to evaluate current design's ease of use.

Please note that we identify this testing as Phase 2. 

### Action Items
- [x] Meet with Design team to understand what Designers would like to be tested from their designs and user flow 
- [x]  Receive an older example of previous CTJ research (with old data) 
- [x] Pilot test with design team: Week of 9/18/23 
- [ ] Participant recruitment (5 participants): Week of 9/18/23 - 9/25/23 #455 
- [ ] Testing (pending participant schedule): Week of 9/25/23 - 10/2/23  [add issue number] 

### Resources/Instructions
- [CTJ: CRM Usability Test Phase 2 General Folder](https://drive.google.com/drive/folders/1fxZoUKCVLNUubeDRFblcgONFGHNcNQMy?usp=drive_link)
- [Phase 2 Usability Testing Results](https://drive.google.com/file/d/1GibVbROw8nXcwzkLoLS0B6RE7ip2pdFq/view?usp=drive_link)
- [OLD CMS Role Posting Test Plan](https://docs.google.com/document/d/1z7xDbp8UeBArZl1u3xFSYFZuuPaHlAbUn1f37FBKXMs/edit)
- List of current projects [Product Management CoP Agenda](https://github.com/hackforla/product-management/issues/131#issuecomment-1656240943)
- [Hack for LA Website](https://www.hackforla.org/projects/)

**Comment by kcoronel** [comment]
Hi @jayywu @ngadoq @Leah0996 @sabheasley I wanted to outline a few updates I made to the issue to make it clearer as well as explain any Kanban guidelines used at Hack for LA. 

Edits Made: 
1. I edited the title of the issue to include (Epic Issue), an epic issue is created when it has a number of workflows associated with them that would need their own issue. Think of workflows as work that may become too 
2. @jayywu I edited the overview a bit, please feel free to edit further, it should be clear enough for someone who is new to the project understands what this issue is about. 
3. 


Guidelines: 
- There should be no more than one person assigned to an issue. 
-

**Comment by sabheasley** [comment]
Hi @jayywu can you please provide updates answering the following questions prior to our meeting, ty!

1. Progress 
2. Blockers 
3. Availability 
4. ETA

**Comment by sabheasley** [comment]
@jayywu can you provide an update to this issue by answering the following?

- Progress:
- Blockers 
- Availability:
- ETA:

**Comment by Leah0996** [comment]
Attached is the results from the usability test @kcoronel 
[HfLA UX Research - CMS Role Posting Phase 2.pdf](https://github.com/hackforla/CivicTechJobs/files/14426618/HfLA.UX.Research.-.CMS.Role.Posting.Phase.2.pdf)

**Comment by kcoronel** [comment]
All tasks have been completed. Closing this issue.
