### ISSUE TITLE
Landing Page: Parsing Figma Design into a development roadmap

### ISSUE THREAD

**Issue by Aveline-art** [hackforla/CivicTechJobs#47]
### Overview

As a developer, we need to have a roadmap for how to implement a new page. For this issue we will examine the design of the landing page, and figure out how to create this page in an organized way so that we make sure the code is as reusable as possible.

### Action Items

- [x] Create one issue per component on the page, if the component is not already created
  - [x] Beyond some functional components, be sure to also standardize title sizes and color scss names 
- [x] Separate the page into multiple pieces and make issues out of them

### Resources/Instructions

[Figma for the landing page](https://www.figma.com/file/G5bOqhud6azbxyR9El9Ygp/Civic-Tech-Jobs?node-id=1%3A7)

**Comment by Aveline-art** [comment]
### Notes on components

- [ ] Responsiveness
- [ ] Reusable -- should this be its own react component?


### Components

- [ ] Header navigation
  - [ ] Must condense into hamburger menu at breakpoints (figma does not show how menu looks like, so let's leave have it do an alert on click) 
- [ ] Buttons (sky blue, dark blue)
  - [ ] Have a version for <a> tags and for <button> tags, since some buttons goes to a different page. 
- [ ] Color palette classes
  - [ ] Black for text
  - [ ] Sky blue for button
  - [ ] Dark blue for button
- [ ] Title sizes classes
- [ ] Circles (for CoPs)
- [ ] Footer navigation
- [ ] Modal card (for circles) -- should this be a wrapper?
  - [ ] Inner modal navigation
  - [ ] Inner modal card      
- [ ] Modal for mobile -- should this be the same as a modal card, only responsive?
- [ ] Text alignment classes
- [ ] Container classes -- is this needed?

### Page portions

- [ ] Top portion (everything above CoP container)
- [ ] CoP portion (only the CoP container)


### Other

- [ ] Logo images and svg
- [ ] Hero image and svg
- [ ] CoP logos

**Comment by Aveline-art** [comment]
Closed because all the issues have been made, namely #60 to #74 all pertains to the landing page.

**Comment by Aveline-art** [comment]
### Planning Notes

- [ ] #60 
- [ ] #61 
- [ ] #62 
- [ ] #63 
- [ ] #64 
- [ ] #65 
- [ ] #66 
- [ ] #67 
- [ ] #68 
- [ ] #69 
- [ ] #70 
- [ ] #71 
- [ ] #72
