### ISSUE TITLE
Outlining new research opportunities for the 2024 Q2 roadmap - this is a practice issue

### ISSUE THREAD

**Issue by jayywu** [hackforla/CivicTechJobs#482]
### Overview
As a strategic research team, uncovering new opportunities require conducting generative research activities such as proactive interviews, experience mapping, and opportunity map prioritization in collaboration with product managers. Since these efforts have a long timeline, and involves multiple teams, team members, and community members, advanced planning, recruiting, and workshopping is needed before the information gathered can be disseminated and leveraged.

### Action Items

- [ ] Research team to align on Q1 meeting schedule
- [ ] Research team members to review existing roadmap and catalog opportunities for additional information
- [ ] Research lead to schedule and lead planning meetings in Q1 2024

### Resources/Instructions
[Opportunity mapping guide](https://www.producttalk.org/2020/07/opportunity-mapping/)
[How to recruit and summarize interview findings](https://www.producttalk.org/2022/12/customer-interviews/)
[Continuous Interview method](https://www.producttalk.org/category/customer-interviews/)

**Comment by kchotani** [comment]
@jayywu Hey, Closing this issue as this is a practice issue. Please let me know if there are any concerns with closing it. Thanks!
