### ISSUE TITLE
Look through closed issues for CTJ highlights for Hack for LA website

### ISSUE THREAD

**Issue by kcoronel** [hackforla/CivicTechJobs#548]
#### Overview 
Need to write up CTJ accomplishments for the years 2021 - 2024 

### Action Items 
- [x] Look through closed issues 
- [x] Write up accomplishments 
- [x] Share with Bonnie

### Resources 
[Hack for LA Accomplishments site](https://www.hackforla.org/about/#accomplishments)

**Comment by kcoronel** [comment]
### 2021 
CTJ was launched in late 2021. The team spent their time defining requirements, securing the domain name, and creating initial visual assets like the logo and landing page UX design.

### 2022
CTJ commenced user research, conducting interviews with key stakeholders to inform platform development, finalized the projects Design System, backed infrastructure, and user flow. The team also made headway designing each page of the product, including the CMS system (the administrative input page that product leads will use to upload their projects open roles).  

### 2023 
CTJ successfully launched the project landing page and a visually engaging "coming soon" page to generate early interest and build anticipation for the full platform launch. Our product stakeholder requested us to include a new requirement to the project that would support organizational goals alongside two other projects (People Depot and VRMS). We launched a staging site for the homepage. 

### 2024 
Stay tuned for our accomplishments of this year.

**Comment by kcoronel** [comment]
hey @bonniewolfe I have written the accomplishments for our project above. Please let me know if you have any comments or suggestions.

**Comment by nooriaali9** [comment]
Shared update with Bonnie, this issue is completed

**Comment by ExperimentsInHonesty** [comment]
Here is where the accomplishments will go https://www.hackforla.org/about/#accomplishments

Please make the language more like a press release.  Keep in mind, this is not on theCTJ website, so it needs context

**Comment by kcoronel** [comment]
1. Format: Add context to each year and then what was accomplished

**Comment by kcoronel** [comment]
While writing this add guidance for how the accomplishment was developed

**Comment by kcoronel** [comment]
Edited: 

2021
In late 2021, CTJ embarked on its journey, laying the groundwork for a transformative platform to help prospective Hack for LA volunteers find interdisciplinary projects that will be useful for their career development while contributing to positive civic impact. 

2022
CTJ initiated user research, conducting insightful interviews with key stakeholders aka our volunteers to shape platform development. The team advanced the site's design and development, aiming to create a high-quality, user-friendly platform.

2023
CTJ successfully launched the project landing page and a visually engaging "coming soon" page to generate early interest and build anticipation for the full platform launch. To further support our volunteers' career development, our product stakeholder requested a new requirement in the form of a Skills Matrix. This dynamic Matrix would help volunteers assess their skills throughout their Hack for LA journey. 


2024
Stay tuned for our accomplishments of this year.

**Comment by kcoronel** [comment]
### Project or CoP's repo issue searches
'Completed': https://github.com/hackforla/CivicTechJobs/issues?q=is%3Aissue+completed+is%3Aclosed+
'Done': https://github.com/hackforla/CivicTechJobs/issues?q=is%3Aissue+done+is%3Aclosed+
'Opportunity': https://github.com/hackforla/CivicTechJobs/issues?q=is%3Aissue+opportunity+is%3Aclosed+
'good job': https://github.com/hackforla/CivicTechJobs/issues?q=is%3Aissue+good+job+is%3Aclosed+

**Comment by kcoronel** [comment]
@kcoronel add accomplishments for 2024

**Comment by Janis-Mollineau** [comment]
Hi @kcoronel. Would any of these be worth mentioning for 2024 accomplishments? 

- [ ] CTJ created a user flow that maps out the entire user journey on the website, to ensure that once the staging environment is deployed the user experience and interactions would be seamless. (https://github.com/hackforla/CivicTechJobs/issues/570)
- [ ] CTJ successfully deployed a staging environment to our personal cloud accounts, enabling us to test and prepare for future updates. We are also working on creating automation scripts to improve the process moving forward. https://github.com/hackforla/CivicTechJobs/issues/585
- [ ] For more streamlined communications and enhanced brand alignment, CTJ updated our visual styling and added more variations to our logos. We also created a reference guide for Typography, Community of Practice cards, and Illustrations/Photos, covering usage guidelines, representation formats, and design specifications. [https://github.com/hackforla/CivicTechJobs/issues/؆](https://github.com/hackforla/CivicTechJobs/issues/%D8%86)
- [ ] CTJ launched MVP 1 with a Skills Matrix for Design, Research, Engineering, Data, Product, and DevOps Communities of Practice. [Discovery Research for CTJ Skills Matrix MVP 2 · Issue #511 · hackforla/CivicTechJobs](https://github.com/hackforla/CivicTechJobs/issues/511)

**Comment by kcoronel** [comment]
Availability for this week: Limited 
My estimated ETA for completing this issue: Going to say by 3/17 

Provide Update
1. Progress: Currently we have accomplishment summaries for years '21 - '23, need to create one for 2024
2. Blockers: None
3. Availability: about 30-min this week and 30-min next week 
4. ETA: 3/17 
5. Pictures: N/A

**Comment by kcoronel** [comment]
Please provide update
1. Progress - No progress. 
2. Blockers - None. 
3. Availability - Can complete this in the next 2 weeks, expect Bonnie to review this after TDM calculator sprint wraps up. Goal is to complete 2024 accomplishment before our monthly meeting with Bonnie 
4. ETA - 2-weeks

**Comment by kcoronel** [comment]
Reviewed with Bonnie live. Suggestion to type this into AI using the 2020 example found on the website. Want to make this exciting and interesting for funders, partners/stakeholders.  

Example: https://github.com/hackforla/website/issues/8288
