### ISSUE TITLE
Roadmap creation for MVP

### ISSUE THREAD

**Issue by nooriaali9** [hackforla/CivicTechJobs#569]
### Overview

- Create a roadmap of where we are and create stories going towards MVP and create timeline
- To get us to the point to release something
- what to prioritize

### Action Items

- [ ] Create Backend, Frontend and Design architecture
- [ ] Create a roadmap
- [ ] Create all stories & store in prioritized backlog 
- [ ] KT to PMs on said updates for MVP

### Resources/Instructions

[Resources](https://hackforla.github.io/CivicTechJobs/resources/)

**Comment by nooriaali9** [comment]
#365 - tracking update of roadmap here

**Comment by kcoronel** [comment]
@LoTerence please share your Dev roadmap here when you have a chance

**Comment by LoTerence** [comment]
Current Dev roadmap:

https://docs.google.com/document/d/1KTElKAprzv46-FqIBBcT5w8fi1oh6b03nCQfvm13XGE/edit?usp=sharing

**Comment by nooriaali9** [comment]
![Image](https://github.com/user-attachments/assets/18ff84f6-0df0-4a7f-8d22-378b6181ea5f)

@kcoronel  This is a draft version of our framework! Let me know if this looks okay to you! Thanks to @LoTerence

**Comment by LoTerence** [comment]
Next steps for application architecture diagram:

- [ ] add more details to the rough draft, make it look prettier
- [ ] write and publish documentation
- [ ] requirement: any new comer or PMs are able to have a good understanding with a quick look

**Comment by nooriaali9** [comment]
@LoTerence 

1. Do you need any help from my end for the above tasks? 
2. Has there been any progress on these tasks since Nov?

Please update / comment accordingly!

**Comment by LoTerence** [comment]
Updates on above 3 tasks: 
- Made a final draft here: https://drive.google.com/file/d/1OBYs5E6UT-d4IbseJMNGyhGbkUH03lXi/view?usp=drive_link
- I included that diagram in the docs
- Updated architecture docs in the dev branch, I just need to merge into main branch to publish it now
- I think most devs should be able to understand the full stack architecture by looking at that diagram now. 

Lmk if you have any questions at all though!

**Comment by kcoronel** [comment]
Missing is AWS architecture - which will come once we have the staging site up

**Comment by Janis-Mollineau** [comment]
@kcoronel Nooria is unassigned to this issue. Should I add you or myself to this issue?

**Comment by kcoronel** [comment]
@snigbehara let's discuss where in your dev timeline this issue falls into

**Comment by jaason-shi** [comment]
1. Progress: Created new and preliminary dev roadmap for May to August. Up for discussion in next PM/Leads meeting.
2. Blockers: Confirming MVP 1 after Leads discussion
3. Availability: Limited (Will not be available June 15th to June 18th)
4. ETA: New draft for next PM meeting (Tuesday)

[CTJ Dev Roadmap](https://docs.google.com/document/d/17yraNdhuH4p3NGCFSgWtMOYX5rMC67jhZO1PWYi5ZCw/edit?tab=t.0#heading=h.k5hwf69dqel0)

**Comment by jaason-shi** [comment]
1. Progress: Updated dev roadmap for June to TBD. Up for discussion in next PM/Leads meeting.
2. Blockers: Confirming deadlines for each phase in upcoming leads discussion
3. Availability: Limited (Will not be available June 15th to June 18th)
4. ETA: New draft for next PM meeting (Tuesday)

[CTJ Dev Roadmap](https://docs.google.com/document/d/17yraNdhuH4p3NGCFSgWtMOYX5rMC67jhZO1PWYi5ZCw/edit?tab=t.0#heading=h.k5hwf69dqel0)

**Comment by jaason-shi** [comment]
1. Progress: Updated dev roadmap. Awaiting feedback from teams.
2. Blockers: Confirming deadlines for each phase in upcoming leads discussion
3. Availability: Limited
4. ETA: Review feedback for next PM meeting

**Comment by kcoronel** [comment]
Hi @jaason-shi please provide update: 
1. Progress 
2. Blockers 
3. Availability 
4. ETA

Do you still need Research + Design to give you feedback?
